"""Generate authored practical guides and an assistant hub; no source files are copied."""
import json,re,sys
from html import escape as e
from pathlib import Path
from urllib.parse import quote
from xml.etree import ElementTree as ET
ROOT=Path(__file__).resolve().parents[1]
packs=json.loads((ROOT/'data/assistant-packs.json').read_text())
template=(ROOT/'konu/akran-zorbaligi/index.html').read_text()
header=re.search(r'<header.*?</header>.*?</nav>',template,re.S).group()
footer=re.search(r'<footer.*?</footer>',template,re.S).group()
outputs={}
def page(path,title,desc,body,extra='',schema=None):
 url='https://pdrkampus.com'+path
 structured='<script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False).replace('<','\\u003c')+'</script>' if schema else ''
 outputs[path.lstrip('/')+'index.html']=f'''<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f6f5f0"><title>{e(title)} | PDR Kampüs</title><meta name="description" content="{e(desc,quote=True)}"><link rel="canonical" href="{url}"><meta property="og:title" content="{e(title)} | PDR Kampüs"><meta property="og:description" content="{e(desc,quote=True)}"><meta property="og:url" content="{url}"><meta property="og:type" content="website"><link rel="stylesheet" href="/src/style.css"><link rel="stylesheet" href="/src/shell-refresh.css"><link rel="stylesheet" href="/src/design-system.css"><link rel="stylesheet" href="/src/topic-page.css"><link rel="stylesheet" href="/src/assistant.css?v=20261006-2">{structured}</head><body id="top">{header}{body}{footer}<script type="module" src="/src/menu.js?v=20261006-2"></script>{extra}</body></html>'''
for p in packs:
 sections=''.join(f'<section class="topic-section"><h2>{e(s["title"])}</h2><p>{e(s["body"])}</p></section>' for s in p['sections'])
 checklist=''.join('<li>'+e(s)+'</li>' for s in p['checklist'])
 steps=''.join('<li>'+e(s)+'</li>' for s in p['activity']['steps'])
 sources=''.join(f'<li><a href="{e(s["url"],quote=True)}" target="_blank" rel="noopener noreferrer">{e(s["title"])}</a></li>' for s in p['sources'])
 adaptation=('Okul öncesi için yetişkinin yönettiği resim ve oyun, ilkokul için somut kısa örnekler, ortaokul ve lise için yazılı düşünme ve grup tartışması kullanılabilir. Uygulama öncesinde süre ve yönergeleri grubunuza uyarlayın.' if p['activity']['audience']=='Öğrenci' else 'Bu örnek '+p['activity']['audience'].lower()+' hazırlık çalışmasıdır. Öğrenciye uygulanan bir ölçek veya sınıf etkinliği olarak kullanılmaz; katılımcıların ihtiyaçlarına göre düzenlenir.')
 related=''.join(f'<a href="{x["path"]}">{e(x["title"])}</a>' for x in packs if x['id']!=p['id'])
 body=f'''<main class="topic-shell"><nav class="topic-breadcrumb" aria-label="İçerik haritası"><a href="/">PDR Kampüs</a><span>/</span><a href="/asistan/">Günlük asistan</a><span>/</span><span>{e(p['category'])}</span></nav><section class="topic-hero"><div><p class="topic-kicker">UYGULAMA REHBERİ · {e(p['category'].upper())}</p><h1>{e(p['title'])}</h1><p class="topic-lead">{e(p['intro'])}</p><p>Güncelleme: 6 Ekim 2026 · PDR Kampüs özgün uygulama taslağı</p></div><aside class="topic-quick"><strong>Okumadan uygulamaya</strong><p>Hazırlık adımlarını haftalık planına taşı; etkinlik taslağını düzenleyip çıktı al.</p><a href="/asistan/#paketler">Çalışma paketini aç →</a></aside></section><section class="topic-content"><article class="topic-article">{sections}<section class="topic-section"><h2>Hazırlık kontrol listesi</h2><ol>{checklist}</ol><a href="/asistan/?paket={p['id']}#planner">İlk adımı haftalık planıma ekle →</a></section><section class="topic-section"><h2>Özgün çalışma örneği: {e(p['activity']['title'])}</h2><p>Katılımcı grubu: {e(p['activity']['audience'])}</p><p>Amaç: {e(p['activity']['goal'])}. Bu örnek hazırlık için sunulur; kademeye uygunluk, kazanım ve erişilebilirlik uygulayıcı tarafından değerlendirilir. Katılım ve kişisel paylaşım zorunlu tutulmaz.</p><ol>{steps}</ol><p>{e(adaptation)}</p><a href="/asistan/#etkinlik">Süre seçerek taslak oluştur →</a></section><section class="topic-section"><h2>Çıktıyı nasıl değerlendirebilirim?</h2><p>Uygulama sonunda isim almadan öğrencilerin öğrendikleri bir noktayı ve hâlâ merak ettikleri bir soruyu alın. Bir hafta sonra kısa izlemeyle becerinin günlük okul yaşamında kullanımını konuşun. Katılım veya etkinlik sayısını tek başına etkililik sonucu olarak sunmayın.</p></section><section class="topic-section"><h2>Resmî kaynak ve taslak ayrımı</h2><p>Yukarıdaki örnek ve kontrol listesi PDR Kampüs tarafından hazırlanmıştır; resmî MEB belgesi veya onaylı psikoeğitim programı değildir. Resmî merkezlerdeki materyalleri kendi yönergeleriyle inceleyin. Öğrenciye özel görüşme notları ve kişisel bilgiler bu sitedeki plan veya taslağa eklenmez.</p><ul>{sources}</ul></section></article><aside class="topic-sidebar"><div class="topic-card"><h2>İlgili çalışmalar</h2><div class="topic-links">{related}</div></div><div class="topic-card"><h2>Kaynaklarını seç</h2><div class="topic-links"><a href="/kutuphane.html?q={quote(p['query'])}">Kütüphanede ilgili resmî materyalleri ara</a><a href="/asistan/#rapor">Aylık faaliyet özeti hazırla</a></div></div></aside></section></main>'''
 schema={'@context':'https://schema.org','@type':'Article','headline':p['title'],'dateModified':p['updatedAt'],'inLanguage':'tr','mainEntityOfPage':'https://pdrkampus.com'+p['path'],'author':{'@type':'Organization','name':'PDR Kampüs'},'publisher':{'@type':'Organization','name':'PDR Kampüs'}}
 page(p['path'],p['title'],p['title']+': hazırlık adımları, özgün etkinlik örneği, kontrol listesi ve resmî kaynak bağlantıları.',body,schema=schema)
links=''.join(f'<li><a href="{p["path"]}">{e(p["title"])}</a></li>' for p in packs)
body='''<main class="assistant-shell"><section class="assistant-hero"><div><p class="eyebrow">PDR KAMPÜS · GÜNLÜK ASİSTAN</p><h1>Kaynağı bul.<br><em>İşini planla, uygulamaya geç.</em></h1><p>Haftalık işleri takip et, sınıf çalışmanı hazırla ve ay sonunda yaptıklarını özetle.</p><nav class="assistant-jumps" aria-label="Asistan araçları"><a href="#planner">Haftalık plan</a><a href="#paketler">Çalışma paketleri</a><a href="#etkinlik">Etkinlik taslağı</a><a href="#rapor">Faaliyet özeti</a></nav></div><aside><span id="todayLabel">Bugünkü çalışma alanın</span><h2>Bugün neyi kolaylaştıralım?</h2><p>Bir öncelik seç. İlk adımı planına ekle. Hazır taslaktan çalışmaya başla.</p><a href="/calisma-alani.html">Çalışma Alanım →</a></aside></section>
<p id="assistantStatus" role="status" aria-live="polite"></p>
<section id="planner" class="assistant-section"><div class="assistant-heading"><div><p class="eyebrow">01 / HAFTALIK PLAN</p><h2>Bu haftaki işlerin</h2><p id="storageMode">Plan bağlantısı hazırlanıyor…</p></div><label>Haftayı seç<input id="weekDate" type="date" required></label></div><div class="assistant-stats"><span><strong id="counttoday">0</strong> bugün bekleyen</span><span><strong id="countoverdue">0</strong> tarihi geçen</span><span><strong id="countopen">0</strong> açık iş</span></div><p class="assistant-note">Yalnız çalışma başlığı gir; öğrenci adı, görüşme içeriği veya sağlık bilgisi ekleme. Misafir işleri bu tarayıcıda saklanır; hesapla girişte ayrı hesap planın açılır. Misafir işler hesaba otomatik aktarılmaz.</p><form id="taskForm" class="assistant-task-form"><label>Yapılacak iş<input name="title" minlength="3" maxlength="180" required placeholder="Örn. 5. sınıf uyum etkinliğini hazırla"></label><label>Tarih<input id="taskDate" name="due_date" type="date"></label><button type="submit" disabled>İş ekle</button></form><h3 id="weekRange">Hafta görünümü</h3><div id="weekBoard" class="assistant-week"><p>Plan yükleniyor…</p></div><details><summary>Diğer tarihler ve tarihsiz işler</summary><div id="otherTasks"></div></details><a href="/hesap.html">Hesabına giriş yap →</a></section>
<section id="paketler" class="assistant-section"><div class="assistant-heading"><div><p class="eyebrow">02 / KAYNAKTAN UYGULAMAYA</p><h2>İhtiyacına göre çalışma paketi</h2><p>Her pakette rehber, kontrol listesi ve özgün etkinlik örneği var.</p></div><span id="packCount">8 çalışma paketi</span></div><div class="assistant-filters"><label>Kademe<select id="packLevel"><option value="">Tüm kademeler</option><option>Okul öncesi</option><option>İlkokul</option><option>Ortaokul</option><option>Lise</option></select></label><label>Paket ara<input id="packSearch" type="search" placeholder="Veli, devamsızlık, zaman yönetimi…"></label></div><div id="packGrid" class="assistant-pack-grid"></div><details><summary>Tüm uygulama rehberleri</summary><ul>'''+links+'''</ul></details></section>
<section id="etkinlik" class="assistant-section"><p class="eyebrow">03 / ETKİNLİK TASLAĞI</p><h2>Sınıf çalışmanı hazırlamaya başla</h2><p>Özgün örneklerden kademeye ve süreye göre bir hazırlık taslağı oluştur. Uygulama öncesinde kazanımı ve yönergeleri grubuna göre düzenle.</p><form id="activityForm" class="assistant-filters"><label>Kademe<select id="activityLevel"><option>İlkokul</option><option>Ortaokul</option><option>Lise</option></select></label><label>Çalışma<select id="activityPack" required><option value="">Paketler yükleniyor…</option></select></label><label>Süre<select id="activityMinutes"><option value="20">20 dakika</option><option value="30" selected>30 dakika</option><option value="40">40 dakika</option></select></label><button type="submit">Taslağı oluştur</button></form></section>
<section id="rapor" class="assistant-section"><p class="eyebrow">04 / AYLIK FAALİYET ÖZETİ</p><h2>Yaptığın çalışmaları görünür kıl</h2><p>Anonim toplamlarla bir özet oluştur. Form ve çıktı sunucuya gönderilmez, tarayıcıda kalıcı olarak saklanmaz; sayfayı kapatmadan indir. Kurumun resmî rapor formatını ayrıca kullan.</p><form id="reportForm"><div class="assistant-filters"><label>Rapor ayı<input type="month" name="month" required></label><label>Bireysel görüşme sayısı<input type="number" name="sessions" min="0" max="100000" step="1" value="0" required></label><label>Sınıf/grup etkinliği sayısı<input type="number" name="activities" min="0" max="100000" step="1" value="0" required></label><label>Veli çalışması sayısı<input type="number" name="parents" min="0" max="100000" step="1" value="0" required></label><label>Öğretmen müşavirliği sayısı<input type="number" name="teachers" min="0" max="100000" step="1" value="0" required></label><label>Toplam etkinlik katılımı<input type="number" name="participations" min="0" max="100000" step="1" value="0" required></label></div><p>Toplam katılım benzersiz kişi sayısı değildir; aynı kişinin farklı etkinliklere katılımı birden fazla sayılabilir.</p><label>Okul programındaki hedef<textarea name="goal" maxlength="1000" placeholder="Kişisel bilgi içermeyen çalışma hedefi"></textarea></label><label>Değerlendirme ve sınırlılıklar<textarea name="evaluation" maxlength="1000" placeholder="Hangi geri bildirim alındı? Değerlendirilmeyen sonuçlar neler?"></textarea></label><label>Sonraki ay önceliği<textarea name="next" maxlength="1000"></textarea></label><button type="submit">Özet taslağını oluştur</button></form></section>
<section id="outputPanel" class="assistant-section" hidden><h2 id="outputTitle" tabindex="-1">Hazırlık taslağın</h2><div class="assistant-actions"><button id="downloadOutput" type="button">Metin olarak indir</button><button id="printOutput" type="button">Yazdır / PDF kaydet</button><button id="copyOutput" type="button">Kopyala</button></div><pre id="outputText"></pre></section><noscript><p>Plan ve taslak araçları için JavaScript gereklidir. Yukarıdaki uygulama rehberlerini JavaScript olmadan da okuyabilirsiniz.</p></noscript></main>'''
page('/asistan/','Rehber Öğretmen Günlük Asistanı','Rehber öğretmenler için haftalık iş planı, kademeye göre etkinlik taslakları, uygulama rehberleri ve aylık faaliyet özeti hazırlama araçları.',body,'<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/dist/umd/supabase.js"></script><script type="module" src="/src/assistant.js?v=20261006-2"></script>')
ns='http://www.sitemaps.org/schemas/sitemap/0.9';ET.register_namespace('',ns);tree=ET.parse(ROOT/'sitemap.xml')
newurls={'https://pdrkampus.com/asistan/',*['https://pdrkampus.com'+p['path'] for p in packs]}
for entry in list(tree.getroot()):
 if entry.find('{'+ns+'}loc').text in newurls:tree.getroot().remove(entry)
for url in sorted(newurls):
 entry=ET.SubElement(tree.getroot(),'{'+ns+'}url');ET.SubElement(entry,'{'+ns+'}loc').text=url;ET.SubElement(entry,'{'+ns+'}lastmod').text='2026-10-06'
tree.getroot()[:]=sorted(tree.getroot(),key=lambda n:n.find('{'+ns+'}loc').text);ET.indent(tree,space='  ')
outputs['sitemap.xml']='<?xml version="1.0" encoding="UTF-8"?>\n'+ET.tostring(tree.getroot(),encoding='unicode')+'\n'
for path,content in outputs.items():
 dest=ROOT/path
 if '--check' in sys.argv:assert dest.exists() and dest.read_text()==content,path
 else:dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(content)
print('Assistant hub and eight practical guides verified.')
