import {documentItems,filterDocuments,documentTypes} from './documents.js';
import {searchCatalogs} from './search.js';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i');
async function loadCatalog(path){return fetch(new URL(path,import.meta.url)).then(r=>{if(!r.ok)throw Error('Katalog yüklenemedi');return r.json()}).catch(()=>[])}
const [tools,library]=await Promise.all([loadCatalog('../data/forms.json?v=20260925-3'),loadCatalog('../data/library.json?v=20260925-3')]);
let group='';
function populateTypes(){const categories=[...new Set(tools.filter(x=>!group||x.group===group).map(x=>x.category))];$('#toolType').innerHTML='<option value="">Tüm alt başlıklar</option>'+categories.map(x=>`<option>${esc(x)}</option>`).join('')}
if ($('#toolGrid')) {populateTypes();$('#allCount').textContent=tools.length;$('#individualCount').textContent=tools.filter(x=>x.group==='Bireyi Tanıma').length;$('#systemCount').textContent=tools.filter(x=>x.group==='Sistem Formları').length;$('#toolTotal').textContent=tools.length+' dosya'}
function formRow(x,reason=""){return `<article class="form-card"><div class="form-card-top"><span>${esc(x.code)}</span><span>${esc(x.fileType)}</span></div><h4>${esc(x.title)}</h4><p>${esc(x.group)} / ${esc(x.category)}</p>${reason?`<p class="match-reason">${esc(reason)}</p>`:""}<div class="form-card-foot"><span>${esc(x.location)}</span><button data-kind="tool" data-id="${esc(x.id)}">Görüntüle ↗</button></div></article>`}
function libraryCard(x,reason=""){return `<article class="card"><div class="card-meta"><span>${esc(x.type)}</span><span>MEB yayını</span></div><h3>${esc(x.title)}</h3><p>${esc(x.topic)} · ${esc(x.area)}</p>${reason?`<p class="match-reason">${esc(reason)}</p>`:""}<div class="card-bottom"><small>${esc(x.level)}</small><button data-kind="library" data-id="${esc(x.id)}">Görüntüle ↗</button></div></article>`}
function renderTools(){const t=tools.filter(x=>(!group||x.group===group)&&(!$('#toolType').value||x.category===$('#toolType').value)&&(!$('#toolLevel').value||x.level===$('#toolLevel').value)&&(!$('#toolLocation').value||x.location===$('#toolLocation').value));$('#toolSummary').textContent=`${t.length} / ${tools.length} dosya gösteriliyor`+(group?' · '+group:'');const types=[...new Set(t.map(x=>x.category))];$('#categoryOverview').innerHTML=types.map(type=>`<button data-category-jump="${esc(type)}">${esc(type)} <strong>${t.filter(x=>x.category===type).length}</strong></button>`).join('');$('#toolGrid').innerHTML=types.length?types.map((type,i)=>`<details class="form-category" id="form-category-${i}" ${i===0||$('#toolType').value===type?'open':''}><summary class="form-category-head"><h3>${esc(type)}</h3><span>${t.filter(x=>x.category===type).length} dosya</span></summary><div class="form-card-grid">${t.filter(x=>x.category===type).map(formRow).join('')}</div></details>`).join(''):'<p class="empty">Bu filtrelerde dosya bulunamadı.</p>'}
function renderLibrary(){let l=library.filter(x=>(!$('#libraryArea').value||x.area===$('#libraryArea').value)&&(!$('#libraryLevel').value||x.level===$('#libraryLevel').value)&&(!$('#libraryTopic').value||x.topic===$('#libraryTopic').value));$('#libraryGrid').innerHTML=l.length?l.map(libraryCard).join(''):'<p>Bu filtrelerde kaynak bulunamadı.</p>'}
const documents=documentItems(tools,library);
if ($('#documentGrid')) {$('#documentTotal').textContent=documents.length+' belge';
$('#documentType').innerHTML+=[...new Set(documents.map(x=>x.type))].sort((a,b)=>documentTypes.indexOf(a)-documentTypes.indexOf(b)).map(x=>`<option>${esc(x)}</option>`).join('');
let documentLimit=18;
function renderDocuments(){const filtered=filterDocuments(documents,{query:$('#documentQuery').value,type:$('#documentType').value,level:$('#documentLevel').value,source:$('#documentSource').value});$('#documentSummary').textContent=`${filtered.length} / ${documents.length} resmî belge gösteriliyor`;$('#documentGrid').innerHTML=filtered.length?filtered.slice(0,documentLimit).map(x=>`<article class="document-card"><div class="document-card-meta"><span>${esc(x.source)}</span><span>${esc(x.type)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.group)} / ${esc(x.topic)}</p><div><small>${esc(x.level)}</small><button data-kind="${x.kind}" data-id="${esc(x.id)}">Görüntüle ↗</button></div></article>`).join(''):'<p class="empty">Bu filtrelerde belge bulunamadı.</p>';$('#documentMore').hidden=filtered.length<=documentLimit;$('#documentMore').textContent=`Daha fazla belge göster (${filtered.length-documentLimit} kaldı)`}
['documentQuery','documentType','documentLevel','documentSource'].forEach(id=>$('#'+id).addEventListener(id==='documentQuery'?'input':'change',()=>{documentLimit=18;renderDocuments()}));
$('#documentMore').addEventListener('click',()=>{documentLimit+=18;renderDocuments()});
renderDocuments();
}
if ($('#toolGrid'))renderTools();if ($('#libraryGrid'))renderLibrary();
if ($('#toolGrid')) {
$('.catalog-sidebar').addEventListener('click',e=>{const b=e.target.closest('[data-group]');if(!b)return;group=b.dataset.group;document.querySelectorAll('.group-button').forEach(x=>x.classList.toggle('active',x===b));populateTypes();renderTools()});
['toolType','toolLevel','toolLocation'].forEach(id=>$('#'+id).addEventListener('change',renderTools));$('#categoryOverview').addEventListener('click',e=>{const b=e.target.closest('[data-category-jump]');if(!b)return;const idx=[...new Set(tools.filter(x=>(!group||x.group===group)&&(!$('#toolType').value||x.category===$('#toolType').value)&&(!$('#toolLevel').value||x.level===$('#toolLevel').value)&&(!$('#toolLocation').value||x.location===$('#toolLocation').value)).map(x=>x.category))].indexOf(b.dataset.categoryJump);(()=>{const section=$('#form-category-'+idx);if(section){section.open=true;section.scrollIntoView({behavior:'smooth',block:'start'})}})()});
}
if ($('#libraryGrid'))['libraryArea','libraryLevel','libraryTopic'].forEach(id=>$('#'+id).addEventListener('change',renderLibrary));
$('#searchForm')?.addEventListener('submit',e=>{e.preventDefault();const q=$('#searchInput').value.trim();if(!q)return;const {parsed,results}=searchCatalogs(q,tools,library);const a=results.filter(r=>r.kind==='form');const b=results.filter(r=>r.kind==='resource');$('#results').hidden=false;$('#searchSummary').textContent=`“${q}” için ${a.length} form ve ${b.length} kaynak bulundu.`;$('#searchContext').innerHTML=[parsed.grade?parsed.grade+'. sınıf':null,parsed.level,parsed.topic?.name].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('');$('#resultGrid').innerHTML=`<section><div class="result-head"><h3>Formlar ve araçlar <span>${a.length}</span></h3><a href="araclar.html">Tüm form kataloğu ↗</a></div><div class="form-card-grid">${a.length?a.slice(0,6).map(r=>formRow(r.item,r.reason)).join(''):'<p class="empty">Bu konuda eşleşen form bulunamadı.</p>'}</div>${a.length>6?`<details class="more-results"><summary>Diğer ${a.length-6} formu göster</summary><div class="form-card-grid">${a.slice(6).map(r=>formRow(r.item,r.reason)).join('')}</div></details>`:''}</section><section><div class="result-head"><h3>Kütüphane kaynakları <span>${b.length}</span></h3><a href="kutuphane.html">Tüm kaynaklar ↗</a></div><div class="card-grid">${b.length?b.slice(0,6).map(r=>libraryCard(r.item,r.reason)).join(''):'<p class="empty">Bu konuda eşleşen kaynak bulunamadı.</p>'}</div>${b.length>6?`<details class="more-results"><summary>Diğer ${b.length-6} kaynağı göster</summary><div class="card-grid">${b.slice(6).map(r=>libraryCard(r.item,r.reason)).join('')}</div></details>`:''}</section>`;$('#results').scrollIntoView({behavior:'smooth'})});
$('#clearSearch')?.addEventListener('click',()=>{$('#results').hidden=true;$('#searchInput').value='';$('#searchInput').focus()});
function openViewer(item){$('#viewerCode').textContent=(item.code?item.code+' · ':'')+item.fileType+' · '+(item.group?item.group+' / '+item.category:item.area+' / '+item.topic);$('#viewerTitle').textContent=item.title;$('#viewerOpen').href=item.file;$('#viewerBody').innerHTML=item.fileType==='PDF'?`<iframe title="${esc(item.title)}" src="${esc(item.file)}#toolbar=1" loading="lazy"></iframe>`:'<div class="file-message"><strong>Excel dosyası</strong><p>Bu dosya tarayıcıda önizlenemez. “Dosyayı aç / indir” ile MEB’deki özgün dosyayı alabilirsiniz.</p></div>';$('#viewerDialog').showModal()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(!b)return;const item=b.dataset.kind==='tool'?tools.find(x=>x.id===b.dataset.id):library.find(x=>x.id===b.dataset.id);if(!item)return;if(item.file){openViewer(item);return}$('#dialogContent').innerHTML=`<p class="eyebrow">ÖRNEK KÜTÜPHANE KAYDI</p><h2>${esc(item.title)}</h2><dl>${[['Tür',item.type],['Kademe',item.level],['Alan',item.area],['Konu',item.topic],['Kaynak',item.source],['Dosya','Henüz eklenmedi']].map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`;$('#detailDialog').showModal()});
$('#closeDialog').addEventListener('click',()=>$('#detailDialog').close());$('#closeViewer').addEventListener('click',()=>{$('#viewerDialog').close();$('#viewerBody').innerHTML=''});$('#viewerDialog').addEventListener('click',e=>{if(e.target===$('#viewerDialog')){$('#viewerDialog').close();$('#viewerBody').innerHTML=''}});$('#menuButton').addEventListener('click',()=>{const m=$('#mobileMenu');m.hidden=!m.hidden;$('#menuButton').setAttribute('aria-expanded',String(!m.hidden))});$('#mobileMenu').addEventListener('click',e=>{if(e.target.closest('a')){$('#mobileMenu').hidden=true;$('#menuButton').setAttribute('aria-expanded','false')}});
