import {library} from './catalog.js';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i');
const tools=await fetch(new URL('../data/forms.json?v=20260925-2',import.meta.url)).then(r=>{if(!r.ok)throw Error('Katalog yüklenemedi');return r.json()}).catch(()=>[]);
let group='';
function populateTypes(){const categories=[...new Set(tools.filter(x=>!group||x.group===group).map(x=>x.category))];$('#toolType').innerHTML='<option value="">Tüm alt başlıklar</option>'+categories.map(x=>`<option>${esc(x)}</option>`).join('')}
populateTypes();
$('#allCount').textContent=tools.length;$('#individualCount').textContent=tools.filter(x=>x.group==='Bireyi Tanıma').length;$('#systemCount').textContent=tools.filter(x=>x.group==='Sistem Formları').length;
$('#toolTotal').textContent=tools.length+' dosya';
function formRow(x){return `<article class="form-card"><div class="form-card-top"><span>${esc(x.code)}</span><span>${esc(x.fileType)}</span></div><h4>${esc(x.title)}</h4><p>${esc(x.group)} / ${esc(x.category)}</p><div class="form-card-foot"><span>${esc(x.location)}</span><button data-kind="tool" data-id="${esc(x.id)}">Görüntüle ↗</button></div></article>`}
function libraryCard(x){return `<article class="card"><div class="card-meta"><span>${esc(x.type)}</span><span>Örnek taslak</span></div><h3>${esc(x.title)}</h3><p>${esc(x.topic)} · ${esc(x.area)}</p><div class="card-bottom"><small>${esc(x.level)}</small><button data-kind="library" data-id="${esc(x.id)}">İncele ↗</button></div></article>`}
function renderTools(){const t=tools.filter(x=>(!group||x.group===group)&&(!$('#toolType').value||x.category===$('#toolType').value)&&(!$('#toolLevel').value||x.level===$('#toolLevel').value)&&(!$('#toolLocation').value||x.location===$('#toolLocation').value));$('#toolSummary').textContent=`${t.length} / ${tools.length} dosya gösteriliyor`+(group?' · '+group:'');const types=[...new Set(t.map(x=>x.category))];$('#categoryOverview').innerHTML=types.map(type=>`<button data-category-jump="${esc(type)}">${esc(type)} <strong>${t.filter(x=>x.category===type).length}</strong></button>`).join('');$('#toolGrid').innerHTML=types.length?types.map((type,i)=>`<section class="form-category" id="form-category-${i}"><div class="form-category-head"><h3>${esc(type)}</h3><span>${t.filter(x=>x.category===type).length} dosya</span></div><div class="form-card-grid">${t.filter(x=>x.category===type).map(formRow).join('')}</div></section>`).join(''):'<p class="empty">Bu filtrelerde dosya bulunamadı.</p>'}
function renderLibrary(){let l=library.filter(x=>(!$('#libraryArea').value||x.area===$('#libraryArea').value)&&(!$('#libraryLevel').value||x.level===$('#libraryLevel').value));$('#libraryGrid').innerHTML=l.length?l.map(libraryCard).join(''):'<p>Bu filtrelerde örnek kayıt bulunamadı.</p>'}
renderTools();renderLibrary();
$('.catalog-sidebar').addEventListener('click',e=>{const b=e.target.closest('[data-group]');if(!b)return;group=b.dataset.group;document.querySelectorAll('.group-button').forEach(x=>x.classList.toggle('active',x===b));populateTypes();renderTools()});
['toolType','toolLevel','toolLocation'].forEach(id=>$('#'+id).addEventListener('change',renderTools));['libraryArea','libraryLevel'].forEach(id=>$('#'+id).addEventListener('change',renderLibrary));$('#categoryOverview').addEventListener('click',e=>{const b=e.target.closest('[data-category-jump]');if(!b)return;const idx=[...new Set(tools.filter(x=>(!group||x.group===group)&&(!$('#toolType').value||x.category===$('#toolType').value)&&(!$('#toolLevel').value||x.level===$('#toolLevel').value)&&(!$('#toolLocation').value||x.location===$('#toolLocation').value)).map(x=>x.category))].indexOf(b.dataset.categoryJump);$('#form-category-'+idx)?.scrollIntoView({behavior:'smooth',block:'start'})});
const aliases={zorbalik:['siddet','sosyometri','gozlem','akran'],akran:['sosyometri','gozlem','siddet'],devamsizlik:['devamsizlik'],kaygi:['riba','siddet'],sinav:['riba'],ogrenci:['ogrenci']};
function score(x,q){const hay=norm([x.title,x.code,x.group,x.category,x.level,x.location,x.topic,x.area,...(x.tags||[])].join(' '));return norm(q).split(/[^a-z0-9]+/).filter(x=>x.length>1&&!['sinifta','sinifi','icin','ile','bir','suphesi'].includes(x)).reduce((n,t)=>n+(hay.includes(t)?3:(aliases[t]||[]).some(k=>hay.includes(k))?1:0),0)}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();const q=$('#searchInput').value.trim();if(!q)return;const a=tools.map(x=>({x,n:score(x,q)})).filter(r=>r.n>0).sort((a,b)=>b.n-a.n).slice(0,12);const b=library.map(x=>({x,n:score(x,q)})).filter(r=>r.n>0).sort((a,b)=>b.n-a.n);$('#results').hidden=false;$('#searchSummary').textContent=`“${q}” için ${a.length} form ve ${b.length} örnek materyal`;$('#resultGrid').innerHTML=`<section><h3>Formlar ve araçlar <span>${a.length}</span></h3><div class="form-card-grid">${a.length?a.map(r=>formRow(r.x)).join(''):'<p class="empty">Eşleşen form yok.</p>'}</div></section><section><h3>Kütüphane taslakları <span>${b.length}</span></h3><div class="card-grid">${b.length?b.map(r=>libraryCard(r.x)).join(''):'<p class="empty">Eşleşen materyal yok.</p>'}</div></section>`;$('#results').scrollIntoView({behavior:'smooth'})});
$('#clearSearch').addEventListener('click',()=>{$('#results').hidden=true;$('#searchInput').value='';$('#searchInput').focus()});
function openViewer(item){$('#viewerCode').textContent=item.code+' · '+item.fileType+' · '+item.group+' / '+item.category;$('#viewerTitle').textContent=item.title;$('#viewerOpen').href=item.file;$('#viewerBody').innerHTML=item.fileType==='PDF'?`<iframe title="${esc(item.title)}" src="${esc(item.file)}#toolbar=1" loading="lazy"></iframe>`:'<div class="file-message"><strong>Excel dosyası</strong><p>Bu dosya tarayıcıda önizlenemez. “Dosyayı aç / indir” ile MEB’deki özgün dosyayı alabilirsiniz.</p></div>';$('#viewerDialog').showModal()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(!b)return;const item=b.dataset.kind==='tool'?tools.find(x=>x.id===b.dataset.id):library.find(x=>x.id===b.dataset.id);if(!item)return;if(b.dataset.kind==='tool'){openViewer(item);return}$('#dialogContent').innerHTML=`<p class="eyebrow">ÖRNEK KÜTÜPHANE KAYDI</p><h2>${esc(item.title)}</h2><dl>${[['Tür',item.type],['Kademe',item.level],['Alan',item.area],['Konu',item.topic],['Kaynak',item.source],['Dosya','Henüz eklenmedi']].map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`;$('#detailDialog').showModal()});
$('#closeDialog').addEventListener('click',()=>$('#detailDialog').close());$('#closeViewer').addEventListener('click',()=>{$('#viewerDialog').close();$('#viewerBody').innerHTML=''});$('#viewerDialog').addEventListener('click',e=>{if(e.target===$('#viewerDialog')){$('#viewerDialog').close();$('#viewerBody').innerHTML=''}});$('#menuButton').addEventListener('click',()=>{const m=$('#mobileMenu');m.hidden=!m.hidden;$('#menuButton').setAttribute('aria-expanded',String(!m.hidden))});$('#mobileMenu').addEventListener('click',e=>{if(e.target.closest('a')){$('#mobileMenu').hidden=true;$('#menuButton').setAttribute('aria-expanded','false')}});
