import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,authConfigured} from './auth-config.js?v=20260925-2';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const client=authConfigured&&window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let user=null,posts=[],comments=[],reactions=[],counts=new Map(),names=new Map();
const status=s=>{$('#feedStatus').textContent=s},date=s=>new Date(s).toLocaleDateString('tr-TR',{day:'numeric',month:'short'});
const author=id=>`<a href="profil.html?id=${encodeURIComponent(id)}">${esc(names.get(id)||'PDR Kampüs üyesi')}</a>`;
async function load(){const [p,c,r]=await Promise.all([
 client.from('community_posts').select('id,author_id,title,body,category,created_at').eq('status','published').order('created_at',{ascending:false}).limit(100),
 client.from('community_comments').select('id,post_id,author_id,body,created_at').eq('status','published').order('created_at',{ascending:true}).limit(1000),
 user?client.from('community_reactions').select('post_id,kind').eq('user_id',user.id).limit(1000):Promise.resolve({data:[],error:null})]);
 if(p.error||c.error||r.error)throw p.error||c.error||r.error;posts=p.data;comments=c.data;reactions=r.data;
 const [votes,people]=await Promise.all([client.rpc('get_community_like_counts',{post_ids:posts.map(x=>x.id)}),client.rpc('get_member_profiles',{member_ids:[...new Set([...posts,...comments].map(x=>x.author_id))]})]);
 if(votes.error||people.error)throw votes.error||people.error;counts=new Map(votes.data.map(x=>[x.post_id,Number(x.like_count)]));names=new Map(people.data.map(x=>[x.id,x.display_name]));render()}
function render(){const query=$('#feedSearch').value.trim().toLocaleLowerCase('tr-TR'),category=$('#feedCategory').value,saved=$('#savedOnly').checked;const list=posts.filter(p=>(!category||p.category===category)&&(!saved||reactions.some(r=>r.post_id===p.id&&r.kind==='save'))&&(!query||`${p.title} ${p.body} ${p.category}`.toLocaleLowerCase('tr-TR').includes(query)));$('#feedCount').textContent=`${list.length} gönderi`;$('#feedPosts').innerHTML=list.length?list.map(p=>{const cs=comments.filter(c=>c.post_id===p.id),liked=reactions.some(r=>r.post_id===p.id&&r.kind==='like'),bookmarked=reactions.some(r=>r.post_id===p.id&&r.kind==='save');return `<article class="question-card" id="gonderi-${esc(p.id)}"><div class="document-card-meta"><span>${esc(p.category)}</span><span>${date(p.created_at)}</span></div><h2>${esc(p.title)}</h2><p class="question-copy">${esc(p.body)}</p><p class="question-author">${author(p.author_id)}</p><div class="feed-actions"><button type="button" data-reaction="like" data-post="${esc(p.id)}" aria-pressed="${liked}" ${!user?'disabled':''}>${liked?'♥':'♡'} Beğen · ${counts.get(p.id)||0}</button><button type="button" data-reaction="save" data-post="${esc(p.id)}" aria-pressed="${bookmarked}" ${!user?'disabled':''}>${bookmarked?'✓ Kaydedildi':'Kaydet'}</button><span>${cs.length} yorum</span></div><div class="question-answers">${cs.map(c=>`<div class="answer-card"><p>${esc(c.body)}</p><div class="answer-footer">${author(c.author_id)} · ${date(c.created_at)}</div></div>`).join('')}</div>${user?`<form data-comment="${esc(p.id)}" class="answer-form"><label>Yorum yaz<textarea name="body" minlength="2" maxlength="2000" required placeholder="Deneyimini paylaş; öğrenciye ait tanınabilir bilgi yazma."></textarea></label><button type="submit">Yorum yap ↗</button></form>`:'<a href="hesap.html">Yorum yapmak için giriş yap ↗</a>'}</article>`}).join(''):'<p>Bu filtreye uygun gönderi bulunamadı.</p>'}
async function verify(){const {data:{user:verified},error}=await client.auth.getUser();if(error||verified?.id!==user?.id)throw Error('Yeniden giriş yap.')}
async function init(){if(!client){status('Topluluk bağlantısı kurulmadı.');return}const {data:{session}}=await client.auth.getSession();user=session?.user||null;$('#feedCompose').hidden=!user;$('#feedLogin').hidden=!!user;$('#savedFilter').hidden=!user;$('#savedOnly').checked=!!user&&new URLSearchParams(location.search).has('kaydedilenler');try{await load()}catch(e){status('Gönderiler yüklenemedi. 012 SQL dosyasını kontrol et: '+e.message)}}
$('#feedSearch').addEventListener('input',render);$('#feedCategory').addEventListener('change',render);$('#savedOnly').addEventListener('change',render);
$('#feedForm').addEventListener('submit',async e=>{e.preventDefault();if(!user)return;const f=e.currentTarget,b=f.querySelector('button[type="submit"]'),title=f.elements.title.value.trim(),body=f.elements.body.value.trim(),category=f.elements.category.value;if(title.length<5||body.length<10)return;b.disabled=true;try{await verify();const {error}=await client.from('community_posts').insert({author_id:user.id,title,body,category});if(error)throw error;f.reset();await load();status('Gönderin yayımlandı.')}catch(e){status(e.message)}finally{b.disabled=false}});
$('#feedPosts').addEventListener('submit',async e=>{const f=e.target.closest('[data-comment]');if(!f)return;e.preventDefault();const b=f.querySelector('button'),body=f.elements.body.value.trim();if(body.length<2)return;b.disabled=true;try{await verify();const {error}=await client.from('community_comments').insert({post_id:f.dataset.comment,author_id:user.id,body});if(error)throw error;await load();status('Yorum yayımlandı.')}catch(e){status(e.message);b.disabled=false}});
$('#feedPosts').addEventListener('click',async e=>{const b=e.target.closest('[data-reaction]');if(!b||!user)return;b.disabled=true;try{const post_id=b.dataset.post,kind=b.dataset.reaction,active=reactions.some(r=>r.post_id===post_id&&r.kind===kind);const {error}=active?await client.from('community_reactions').delete().eq('post_id',post_id).eq('user_id',user.id).eq('kind',kind):await client.from('community_reactions').insert({post_id,user_id:user.id,kind});if(error)throw error;await load()}catch(e){status(e.message);b.disabled=false}});
await init();
