import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,authConfigured} from './auth-config.js?v=20260925-2';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&quot;',"'":'&#39;'}[c]));
const client=authConfigured&&window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let user=null,items=[],names=new Map(),unreadOnly=true;
const labels={question_answer:'Soruna yeni cevap',post_comment:'Gönderine yeni yorum',document_approved:'Belgen yayımlandı',document_rejected:'Belgen reddedildi',document_archived:'Belgen yayından kaldırıldı'};
const links={question_answer:id=>`soru.html?id=${encodeURIComponent(id)}`,post_comment:id=>`gonderi.html?id=${encodeURIComponent(id)}`,document_approved:()=> 'profil.html#belgelerim',document_rejected:()=> 'profil.html#belgelerim',document_archived:()=> 'profil.html#belgelerim'};
const status=s=>{$('#notificationStatus').textContent=s};
function render(){const unread=items.filter(x=>!x.read_at).length,$list=$('#notificationList');$('#unreadCount').textContent=String(unread);$('#markAllRead').disabled=!unread;$('#unreadTab').classList.toggle('active',unreadOnly);$('#allTab').classList.toggle('active',!unreadOnly);const visible=unreadOnly?items.filter(x=>!x.read_at):items;$list.innerHTML=visible.length?visible.map(x=>{const name=x.actor_id?names.get(x.actor_id):null,href=links[x.kind]?.(x.target_id)||'profil.html';return `<article class="notification-row ${x.read_at?'is-read':''}"><span class="notification-dot" aria-hidden="true"></span><div><strong>${esc(labels[x.kind]||'Yeni bildirim')}</strong><p>${name?esc(name)+' · ':''}${new Date(x.created_at).toLocaleString('tr-TR',{dateStyle:'medium',timeStyle:'short'})}</p></div><a href="${href}" data-notification-open="${x.id}">İçeriğe git ↗</a>${x.read_at?'':`<button data-mark-read="${x.id}" type="button">Okundu</button>`}</article>`}).join(''):`<p class="workspace-empty">${unreadOnly?'Okunmamış bildirimin yok.':'Henüz bildirimin yok.'}</p>`}
async function load(){const {data,error}=await client.from('notifications').select('id,actor_id,kind,target_id,created_at,read_at').order('created_at',{ascending:false}).limit(100);if(error)throw error;items=data;const ids=[...new Set(data.map(x=>x.actor_id).filter(Boolean))];names=new Map();if(ids.length){const {data:profiles}=await client.rpc('get_member_profiles',{member_ids:ids});names=new Map((profiles||[]).map(x=>[x.id,x.display_name]))}render()}
async function mark(id){const {error}=await client.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id);if(error)throw error;const item=items.find(x=>x.id===id);if(item)item.read_at=new Date().toISOString();render()}
async function init(){if(!client){status('Bildirim bağlantısı kurulmadı.');return}const {data:{session}}=await client.auth.getSession();user=session?.user||null;$('#notificationLogin').hidden=!!user;$('#notificationArea').hidden=!user;if(!user)return;try{await load()}catch(e){status('Bildirimler yüklenemedi. 016 SQL dosyasını kontrol et: '+e.message)}}
$('#unreadTab').addEventListener('click',()=>{unreadOnly=true;render()});$('#allTab').addEventListener('click',()=>{unreadOnly=false;render()});
$('#markAllRead').addEventListener('click',async e=>{const button=e.currentTarget;button.disabled=true;try{const {error}=await client.from('notifications').update({read_at:new Date().toISOString()}).is('read_at',null);if(error)throw error;await load();status('Tümü okundu olarak işaretlendi.')}catch(err){status(err.message)}finally{button.disabled=false}});
$('#notificationList').addEventListener('click',async e=>{const open=e.target.closest('[data-notification-open]'),button=e.target.closest('[data-mark-read]');if(!open&&!button)return;e.preventDefault();const id=Number((open||button).dataset.notificationOpen||(open||button).dataset.markRead);try{if(!items.find(x=>x.id===id)?.read_at)await mark(id);if(open)location.href=open.href}catch(err){status(err.message)}});
await init();
