import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,authConfigured} from './auth-config.js?v=20260925-2';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const client=authConfigured&&window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const id=new URLSearchParams(location.search).get('id');
const date=s=>new Date(s).toLocaleDateString('tr-TR',{day:'numeric',month:'long',year:'numeric'});
let user=null,post=null,reactions=[],commentOffset=0,commentCount=0;
const names=new Map(),status=s=>{$('#postStatus').textContent=s};
function member(id){return `<a href="profil.html?id=${encodeURIComponent(id)}">${esc(names.get(id)||'PDR Kampüs üyesi')}</a>`}
async function getNames(ids){const missing=[...new Set(ids)].filter(x=>x&&!names.has(x));if(!missing.length)return;const {data,error}=await client.rpc('get_member_profiles',{member_ids:missing});if(error)throw error;for(const x of data||[])names.set(x.id,x.display_name)}
async function getReactions(){if(!user)return;const {data,error}=await client.from('community_reactions').select('kind').eq('post_id',id).eq('user_id',user.id);if(error)throw error;reactions=data||[]}
async function renderVotes(){const {data,error}=await client.rpc('get_community_like_counts',{post_ids:[id]});if(error)throw error;const liked=reactions.some(x=>x.kind==='like'),saved=reactions.some(x=>x.kind==='save');$('#postLike').textContent=`${liked?'♥':'♡'} Beğen · ${Number(data?.[0]?.like_count||0)}`;$('#postLike').setAttribute('aria-pressed',liked);$('#postSave').textContent=saved?'✓ Kaydedildi':'◇ Kaydet';$('#postSave').setAttribute('aria-pressed',saved);$('#postLike').disabled=!user;$('#postSave').disabled=!user}
async function loadReplies(append=false){if(!append){commentOffset=0;$('#replyList').innerHTML=''}const {data,error,count}=await client.from('community_comments').select('id,author_id,body,created_at',{count:'exact'}).eq('post_id',id).eq('status','published').order('created_at',{ascending:true}).range(commentOffset,commentOffset+29);if(error)throw error;const rows=data||[];await getNames(rows.map(x=>x.author_id));commentCount=count||0;$('#replyCount').textContent=commentCount;$('#replyList').insertAdjacentHTML('beforeend',rows.map(x=>`<div class="post-reply"><span class="post-reply-avatar" aria-hidden="true">${esc((names.get(x.author_id)||'P').slice(0,1).toLocaleUpperCase('tr-TR'))}</span><div><div class="post-reply-meta">${member(x.author_id)}<small>${date(x.created_at)}</small></div><p>${esc(x.body)}</p><button type="button" class="report-action" data-report-type="comment" data-report-id="${esc(x.id)}">Bildir</button></div></div>`).join(''));commentOffset+=rows.length;$('#replyMore').hidden=commentOffset>=commentCount;if(!commentCount)$('#replyList').innerHTML='<p>Henüz yanıt yok. İlk yanıtı sen yazabilirsin.</p>'}
async function init(){if(!client||!id){status('Gönderi açılamadı.');return}try{const {data:{session}}=await client.auth.getSession();user=session?.user||null;const {data,error}=await client.from('community_posts').select('id,author_id,title,body,category,school_level,topic_tag,created_at').eq('id',id).eq('status','published').single();if(error||!data){status('Gönderi bulunamadı veya yayından kaldırıldı.');return}post=data;await getNames([post.author_id]);await getReactions();$('#postBreadcrumb').textContent=post.category;$('#postCategory').textContent=[...new Set([post.category,post.school_level,post.topic_tag].filter(Boolean))].join(' · ');$('#postTitle').textContent=post.title;document.title=post.title+' — PDR Kampüs';$('#postBody').textContent=post.body;$('#postAvatar').textContent=(names.get(post.author_id)||'P').slice(0,1).toLocaleUpperCase('tr-TR');$('#postAuthor').textContent=names.get(post.author_id)||'PDR Kampüs üyesi';$('#postAuthor').href='profil.html?id='+encodeURIComponent(post.author_id);$('#postDate').textContent=date(post.created_at)+' · Meslektaş paylaşımı';$('#postReport').dataset.reportId=id;await Promise.all([renderVotes(),loadReplies()]);$('#postArticle').hidden=false;$('#replySection').hidden=false;$('#postReplyForm').hidden=!user;$('#replyLogin').hidden=!!user;status('')}catch(error){status('Gönderi yüklenemedi: '+error.message)}}
async function verify(){const {data:{user:verified},error}=await client.auth.getUser();if(error||verified?.id!==user?.id)throw Error('Yeniden giriş yap.')}
async function toggle(kind,button){if(!user)return;button.disabled=true;try{await verify();const active=reactions.some(x=>x.kind===kind);const q=active?client.from('community_reactions').delete().eq('post_id',id).eq('user_id',user.id).eq('kind',kind):client.from('community_reactions').insert({post_id:id,user_id:user.id,kind});const {error}=await q;if(error)throw error;await getReactions();await renderVotes()}catch(error){status(error.message)}finally{button.disabled=false}}
$('#postLike').addEventListener('click',e=>toggle('like',e.currentTarget));$('#postSave').addEventListener('click',e=>toggle('save',e.currentTarget));
$('#postReplyJump').addEventListener('click',()=>{if(user){$('#replyBody').focus();$('#postReplyForm').scrollIntoView({block:'center'})}else location.href='hesap.html'});
$('#postShare').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);$('#postShare').textContent='Bağlantı kopyalandı ✓'}catch{status('Bağlantı kopyalanamadı.')}});
$('#replyMore').addEventListener('click',async e=>{e.currentTarget.disabled=true;try{await loadReplies(true)}catch(error){status(error.message)}finally{e.currentTarget.disabled=false}});
$('#postReplyForm').addEventListener('submit',async e=>{e.preventDefault();if(!user)return;const form=e.currentTarget,body=form.elements.body.value.trim(),button=form.querySelector('[type="submit"]');if(body.length<2)return;button.disabled=true;try{await verify();const {error}=await client.from('community_comments').insert({post_id:id,author_id:user.id,body});if(error)throw error;form.reset();await loadReplies();status('Yanıtın yayımlandı.')}catch(error){status(error.message)}finally{button.disabled=false}});
await init();
