import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,authConfigured} from './auth-config.js?v=20260925-2';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const client=authConfigured&&window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY),bucket='community-documents';
let user=null,moderator=false;
const statusLabel={pending:'İncelemede',approved:'Yayında',rejected:'Reddedildi',archived:'Yayından kaldırıldı'};
const targetId=new URLSearchParams(location.search).get('id');
const ownCard=x=>`<article class="document-card"><div class="document-card-meta"><span>${esc(statusLabel[x.review_status]||x.review_status)}</span><span>${esc(x.document_type)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.topic)} · ${esc(x.level)}</p>${x.review_status==='rejected'&&x.review_note?`<p class="review-reason">Gerekçe: ${esc(x.review_note)}</p>`:''}<div><small>${new Date(x.created_at).toLocaleDateString('tr-TR')}</small><button data-profile-file="${esc(x.file_storage_key)}">Dosyayı aç ↗</button></div></article>`;
async function memberName(id){const {data,error}=await client.rpc('get_member_profiles',{member_ids:[id]});if(error)throw error;return data?.[0]?.display_name||null}
async function showPublic(id){const name=await memberName(id);$('#memberName').textContent=name||'Üye bulunamadı';if(!name)return;$('#publicArea').hidden=false;const {data,error}=await client.from('community_documents').select('title,document_type,level,topic,file_storage_key,review_status,created_at').eq('uploader_id',id).eq('review_status','approved').order('created_at',{ascending:false}).limit(30);if(error)throw error;$('#memberDocuments').innerHTML=data.length?data.map(ownCard).join(''):'<p>Henüz yayımlanmış belge yok.</p>'}
async function showOwn(){const {data:profile,error:profileError}=await client.from('profiles').select('display_name').eq('id',user.id).single();if(profileError)throw profileError;$('#memberName').textContent=profile.display_name;$('#newDisplayName').value=profile.display_name;$('#ownerArea').hidden=false;const {data,error}=await client.from('community_documents').select('title,document_type,level,topic,file_storage_key,review_status,review_note,created_at').eq('uploader_id',user.id).order('created_at',{ascending:false}).limit(50);if(error)throw error;$('#ownDocuments').innerHTML=data.length?data.map(ownCard).join(''):'<p>Henüz belge göndermedin. Belge Merkezi’nden paylaşabilirsin.</p>'}
const types=['Sunum','Etkinlik','Çalışma kağıdı','Veli materyali','Öğretmen materyali','Diğer'],levels=['Okul öncesi','İlkokul','Ortaokul','Lise','Tüm kademeler'];
function adminCard(x){return `<details class="review-card" data-admin-id="${esc(x.id)}"><summary><span class="review-state">${esc(statusLabel[x.review_status]||x.review_status)}</span><strong>${esc(x.title)}</strong><small>${esc(x.document_type)} · ${esc(x.level)} · ${new Date(x.created_at).toLocaleDateString("tr-TR")}</small></summary><button type="button" data-profile-file="${esc(x.file_storage_key)}">Dosyayı aç ↗</button><label>Başlık<input name="title" value="${esc(x.title)}" minlength="5" maxlength="180"></label><label>Tür<select name="document_type">${types.map(v=>`<option ${v===x.document_type?'selected':''}>${esc(v)}</option>`).join('')}</select></label><label>Kademe<select name="level">${levels.map(v=>`<option ${v===x.level?'selected':''}>${esc(v)}</option>`).join('')}</select></label><label>Konu<input name="topic" value="${esc(x.topic)}" minlength="2" maxlength="80"></label><label>İnceleme notu<textarea name="review_note" rows="2" maxlength="500" placeholder="Ret için gerekçe yaz">${esc(x.review_note||'')}</textarea></label><div class="review-actions"><button type="button" data-admin-action="save">Düzelt</button>${x.review_status!=='approved'?'<button type="button" data-admin-action="approved">Yayımla</button>':''}${x.review_status!=='rejected'?'<button type="button" data-admin-action="rejected">Reddet</button>':''}${x.review_status!=='archived'?'<button type="button" data-admin-action="archived">Sil · geri alınabilir</button>':''}</div></details>`}
async function showAdmin(){const {data,error}=await client.from('community_documents').select('id,title,document_type,level,topic,original_filename,file_storage_key,review_status,review_note,created_at').order('created_at',{ascending:false}).limit(100);if(error)throw error;$('#adminStatus').textContent=`${data.filter(x=>x.review_status==='pending').length} belge inceleme bekliyor.`;$('#adminDocuments').innerHTML=data.length?data.map(adminCard).join(''):'<p>Belge yok.</p>'}
if(!client){$('#memberName').textContent='Profil sistemi kurulmadı.'}
else try{const {data:{session}}=await client.auth.getSession();user=session?.user||null;if(targetId&&targetId!==user?.id){await showPublic(targetId)}else if(user){await showOwn();const {data}=await client.rpc('is_community_moderator');if(data){moderator=true;$('#adminArea').hidden=false;$('#communityAdminLink').hidden=false;await showAdmin()}}else{$('#memberName').textContent='Profilini görmek için giriş yap';$('#profileHint').innerHTML='<a href="hesap.html">Giriş yap ↗</a>'}}catch(error){$('#profileHint').textContent='Profil yüklenemedi: '+error.message}
$('#nameForm').addEventListener('submit',async e=>{e.preventDefault();if(!user)return;const name=$('#newDisplayName').value.trim();if(name.length<2)return;const {error}=await client.from('profiles').update({display_name:name}).eq('id',user.id);$('#nameStatus').textContent=error?error.message:'Adın güncellendi.';if(!error)$('#memberName').textContent=name});
document.addEventListener('click',async e=>{const button=e.target.closest('[data-profile-file]');if(!button||!client)return;button.disabled=true;try{const {data,error}=await client.storage.from(bucket).createSignedUrl(button.dataset.profileFile,300);if(error)throw error;const file=button.dataset.profileFile,title=button.closest('article')?.querySelector('h3,input[name="title"]')?.value||button.closest('article')?.querySelector('h3')?.textContent||'Meslektaş belgesi';$('#viewerCode').textContent='MESLEKTAŞ PAYLAŞIMI · '+(file.endsWith('.pdf')?'PDF':'DOSYA');$('#viewerTitle').textContent=title;$('#viewerOpen').href=data.signedUrl;$('#viewerBody').innerHTML=file.endsWith('.pdf')?`<iframe title="${esc(title)}" src="${esc(data.signedUrl)}#toolbar=1" loading="lazy"></iframe>`:'<div class="file-message"><p>Önizleme yok. Dosyayı alt bağlantıdan aç veya indir.</p></div>';$('#viewerDialog').showModal()}catch(error){$('#profileHint').textContent='Dosya açılamadı: '+error.message}finally{button.disabled=false}});
document.addEventListener('click',async e=>{const button=e.target.closest('[data-admin-action]');if(!button||!moderator||!user)return;const card=button.closest('[data-admin-id]'),action=button.dataset.adminAction,note=card.querySelector('[name="review_note"]').value.trim();if(action==='rejected'&&!note){$('#adminStatus').textContent='Reddetmek için gerekçe yaz.';return}const payload=action==='save'?{title:card.querySelector('[name="title"]').value.trim(),document_type:card.querySelector('[name="document_type"]').value,level:card.querySelector('[name="level"]').value,topic:card.querySelector('[name="topic"]').value.trim()}:{review_status:action,reviewer_id:user.id,reviewed_at:new Date().toISOString(),review_note:note||'İçerik incelendi'};if(action==='save'&&(payload.title.length<5||payload.topic.length<2)){$('#adminStatus').textContent='Başlık en az 5, konu en az 2 karakter olmalı.';return}button.disabled=true;$('#adminStatus').textContent='Kaydediliyor…';try{const {data:{user:verified},error:authError}=await client.auth.getUser();if(authError||verified?.id!==user.id)throw Error('Yeniden giriş yap.');const {data,error}=await client.from('community_documents').update(payload).eq('id',card.dataset.adminId).select('id');if(error)throw error;if(!data.length)throw Error('Belge güncellenemedi.');await Promise.all([showAdmin(),showOwn()]);$('#adminStatus').textContent=action==='save'?'Bilgiler düzeltildi.':action==='archived'?'Belge yayından kaldırıldı.':'Karar kaydedildi.'}catch(error){$('#adminStatus').textContent=error.message;button.disabled=false}});
$('#closeViewer').addEventListener('click',()=>{$('#viewerDialog').close();$('#viewerBody').innerHTML=''});
