import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,authConfigured} from './auth-config.js?v=20260925-2';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const client=authConfigured&&window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const id=new URLSearchParams(location.search).get('id');
const date=s=>new Date(s).toLocaleDateString('tr-TR',{day:'numeric',month:'long',year:'numeric'});
let user=null,question=null,answers=[],visible=30,counts=new Map(),votes=new Set(),names=new Map();
const status=s=>{$('#detailStatus').textContent=s};
async function verify(){const {data:{user:verified},error}=await client.auth.getUser();if(error||verified?.id!==user?.id)throw Error('Yeniden giriş yap.')}
async function loadAnswers(){const {data,error}=await client.from('colleague_answers').select('id,question_id,author_id,body,created_at').eq('question_id',id).eq('moderation_status','published').order('created_at',{ascending:true}).limit(1000);if(error)throw error;answers=data||[];const ids=answers.map(x=>x.id),authors=[...new Set(answers.map(x=>x.author_id).filter(x=>!names.has(x)))];const [tally,people,mine]=await Promise.all([ids.length?client.rpc('get_helpful_counts',{answer_ids:ids}):{data:[],error:null},authors.length?client.rpc('get_member_profiles',{member_ids:authors}):{data:[],error:null},user?client.from('colleague_helpful_votes').select('answer_id').eq('voter_id',user.id).limit(5000):{data:[],error:null}]);if(tally.error||people.error||mine.error)throw tally.error||people.error||mine.error;counts=new Map((tally.data||[]).map(x=>[x.answer_id,Number(x.vote_count)]));for(const x of people.data||[])names.set(x.id,x.display_name);votes=new Set((mine.data||[]).map(x=>x.answer_id));renderAnswers()}
function renderAnswers(){const sort=$('#answerSort').value,rows=[...answers].sort((a,b)=>sort==='helpful'?(counts.get(b.id)||0)-(counts.get(a.id)||0)||new Date(a.created_at)-new Date(b.created_at):new Date(b.created_at)-new Date(a.created_at));$('#answerCount').textContent=answers.length;$('#answerList').innerHTML=rows.length?rows.slice(0,visible).map(a=>{const name=names.get(a.author_id)||'PDR Kampüs üyesi',count=counts.get(a.id)||0,selected=votes.has(a.id);return `<article class="post-reply" id="cevap-${esc(a.id)}"><span class="post-reply-avatar" aria-hidden="true">${esc(name.slice(0,1).toLocaleUpperCase('tr-TR'))}</span><div><div class="post-reply-meta"><a href="profil.html?id=${encodeURIComponent(a.author_id)}">${esc(name)}</a><small>${date(a.created_at)}</small></div><p>${esc(a.body)}</p><div class="question-answer-actions"><button type="button" data-helpful="${esc(a.id)}" aria-pressed="${selected}" ${!user||a.author_id===user.id?'disabled':''}>${selected?'✓ ':''}Faydalı buldum · ${count}</button><button type="button" class="report-action" data-report-type="answer" data-report-id="${esc(a.id)}">Bildir</button></div></div></article>`}).join(''):'<p>Henüz cevap yok. İlk cevabı sen yazabilirsin.</p>';$('#answerMore').hidden=visible>=answers.length}
async function init(){if(!client||!id){status('Soru açılamadı.');return}try{const {data:{session}}=await client.auth.getSession();user=session?.user||null;const {data,error}=await client.from('colleague_questions').select('id,author_id,title,body,category,school_level,topic_tag,created_at').eq('id',id).eq('moderation_status','published').single();if(error||!data){status('Soru bulunamadı veya yayından kaldırıldı.');return}question=data;const {data:people,error:peopleError}=await client.rpc('get_member_profiles',{member_ids:[question.author_id]});if(peopleError)throw peopleError;for(const x of people||[])names.set(x.id,x.display_name);const name=names.get(question.author_id)||'PDR Kampüs üyesi';$('#questionBreadcrumb').textContent=question.category;$('#questionCategory').textContent=[...new Set([question.category,question.school_level,question.topic_tag].filter(Boolean))].join(' · ');$('#questionTitle').textContent=question.title;document.title=question.title+' — PDR Kampüs';$('#questionAvatar').textContent=name.slice(0,1).toLocaleUpperCase('tr-TR');$('#questionAuthor').textContent=name;$('#questionAuthor').href='profil.html?id='+encodeURIComponent(question.author_id);$('#questionDate').textContent=date(question.created_at)+' · Meslektaş sorusu';$('#questionBody').textContent=question.body;$('#questionReport').dataset.reportId=id;await loadAnswers();$('#questionArticle').hidden=false;$('#answerSection').hidden=false;$('#answerForm').hidden=!user;$('#answerLogin').hidden=!!user;status('')}catch(error){status('Soru yüklenemedi: '+error.message)}}
$('#answerSort').addEventListener('change',renderAnswers);$('#answerMore').addEventListener('click',()=>{visible+=30;renderAnswers()});
$('#questionReplyJump').addEventListener('click',()=>{if(user){$('#answerBody').focus();$('#answerForm').scrollIntoView({block:'center'})}else location.href='hesap.html'});
$('#questionShare').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);$('#questionShare').textContent='Bağlantı kopyalandı ✓'}catch{status('Bağlantı kopyalanamadı.')}});
$('#answerList').addEventListener('click',async e=>{const button=e.target.closest('[data-helpful]');if(!button||!user)return;button.disabled=true;try{await verify();const answer_id=button.dataset.helpful,selected=votes.has(answer_id);const {error}=selected?await client.from('colleague_helpful_votes').delete().eq('answer_id',answer_id).eq('voter_id',user.id):await client.from('colleague_helpful_votes').insert({answer_id,voter_id:user.id});if(error)throw error;await loadAnswers()}catch(error){status(error.message);button.disabled=false}});
$('#answerForm').addEventListener('submit',async e=>{e.preventDefault();if(!user)return;const form=e.currentTarget,body=form.elements.body.value.trim(),button=form.querySelector('[type="submit"]');if(body.length<10)return;button.disabled=true;try{await verify();const {error}=await client.from('colleague_answers').insert({question_id:id,author_id:user.id,body});if(error)throw error;form.reset();visible=30;await loadAnswers();status('Cevabın yayımlandı.')}catch(error){status(error.message)}finally{button.disabled=false}});
await init();
