import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,authConfigured} from './auth-config.js?v=20260925-2';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const client=authConfigured&&window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let user=null,questions=[],answers=[],votes=[],counts=new Map(),names=new Map();
const date=s=>new Date(s).toLocaleDateString('tr-TR',{day:'numeric',month:'short',year:'numeric'});
const author=id=>`<a href="profil.html?id=${encodeURIComponent(id)}">${esc(names.get(id)||'PDR Kampüs üyesi')}</a>`;
const notice=(s)=>{$('#questionStatus').textContent=s};
async function load(){const [q,a]=await Promise.all([client.from('colleague_questions').select('id,author_id,title,body,category,school_level,topic_tag,created_at').eq('moderation_status','published').order('created_at',{ascending:false}).limit(100),client.from('colleague_answers').select('question_id').eq('moderation_status','published').limit(1000)]);if(q.error||a.error)throw q.error||a.error;questions=q.data||[];answers=a.data||[];const ids=[...new Set(questions.map(x=>x.author_id))];names=new Map();if(ids.length){const {data,error}=await client.rpc('get_member_profiles',{member_ids:ids});if(error)throw error;names=new Map((data||[]).map(x=>[x.id,x.display_name]))}render()}
function render(){const search=$('#questionSearch').value.trim().toLocaleLowerCase('tr-TR'),category=$('#questionCategory').value;const filtered=questions.filter(q=>(!category||q.category===category)&&(!search||`${q.title} ${q.body} ${q.category}`.toLocaleLowerCase('tr-TR').includes(search)));$('#questionCount').textContent=`${filtered.length} soru`;$('#questions').innerHTML=filtered.length?filtered.map(q=>{const count=answers.filter(a=>a.question_id===q.id).length,href=`soru.html?id=${encodeURIComponent(q.id)}`;return `<article class="question-card" id="soru-${esc(q.id)}"><div class="document-card-meta"><span>${esc(q.category)}${q.school_level&&q.school_level!==q.category?' · '+esc(q.school_level):''}${q.topic_tag?' · '+esc(q.topic_tag):''}</span><span>${date(q.created_at)}</span></div><h2><a href="${href}">${esc(q.title)}</a></h2><p class="question-copy">${esc(q.body)}</p><p class="question-author">Soran: ${author(q.author_id)}</p><div class="feed-actions"><a href="${href}">${count} cevabı gör ↗</a><button type="button" class="report-action" data-report-type="question" data-report-id="${esc(q.id)}">Bildir</button></div></article>`}).join(''):'<p>Bu aramaya uygun soru bulunamadı.</p>';if(location.hash.startsWith('#soru-'))requestAnimationFrame(()=>document.getElementById(decodeURIComponent(location.hash.slice(1)))?.scrollIntoView({block:'start'}))}
async function init(){if(!client){notice('Topluluk bağlantısı kurulmadı.');return}const {data:{session}}=await client.auth.getSession();user=session?.user||null;$('#questionFormArea').hidden=!user;$('#loginPrompt').hidden=!!user;try{await load()}catch(e){notice('Sorular yüklenemedi. Veritabanında 010 SQL dosyasının çalıştırıldığını kontrol et: '+e.message)}}
$('#questionSearch').addEventListener('input',render);$('#questionCategory').addEventListener('change',render);
$('#questionForm').addEventListener('submit',async e=>{e.preventDefault();if(!user)return;const form=e.currentTarget,button=form.querySelector('button[type="submit"]'),title=form.elements.title.value.trim(),body=form.elements.body.value.trim(),category=form.elements.category.value,school_level=form.elements.school_level.value||null,topic_tag=form.elements.topic_tag.value||null;if(title.length<10||body.length<20)return;button.disabled=true;try{const {data:{user:verified}}=await client.auth.getUser();if(verified?.id!==user.id)throw Error('Yeniden giriş yap.');const {error}=await client.from('colleague_questions').insert({author_id:user.id,title,body,category,school_level,topic_tag});if(error)throw error;form.reset();notice('Sorun yayımlandı.');await load()}catch(e){notice(e.message)}finally{button.disabled=false}});
await init();
