import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,authConfigured} from './auth-config.js?v=20260925-2';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&quot;',"'":'&#39;'}[c]));
const client=authConfigured&&window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let user=null,reports=[],parents=new Map();const status=s=>{$('#reportAdminStatus').textContent=s};
const targets={post:id=>`topluluk.html#gonderi-${encodeURIComponent(id)}`,comment:()=> 'topluluk.html',question:id=>`meslektasima-sor.html#soru-${encodeURIComponent(id)}`,answer:()=> 'meslektasima-sor.html',document:()=> 'profil.html'};
const labels={post:'Gönderi',comment:'Yorum',question:'Soru',answer:'Cevap',document:'Meslektaş belgesi'};
function render(){const filter=$('#reportFilter').value,list=reports.filter(x=>!filter||x.status===filter);$('#reportAdminList').innerHTML=list.length?list.map(x=>`<article class="report-row"><div><span class="resource-status ${x.status==='open'?'archived':'published'}">${x.status==='open'?'İncelemede':x.status==='resolved'?'İşlem yapıldı':'İşlem gerekmiyor'}</span><strong>${esc(labels[x.target_type])} · ${esc(x.reason)}</strong><small>${new Date(x.created_at).toLocaleString('tr-TR')}</small>${x.details?`<p>${esc(x.details)}</p>`:''}</div><div class="report-row-actions"><a href="${targets[x.target_type]?.(parents.get(x.target_id)||x.target_id)||'profil.html'}">İçeriğe git ↗</a>${x.status==='open'?`<button data-report-decision="resolved" data-report-id="${esc(x.id)}">İşlem yapıldı</button><button data-report-decision="dismissed" data-report-id="${esc(x.id)}">İşlem gerekmiyor</button>`:`<button data-report-decision="open" data-report-id="${esc(x.id)}">Yeniden aç</button>`}</div></article>`).join(''):'<p>Bu filtrede bildirim yok.</p>';status(`${reports.filter(x=>x.status==='open').length} içerik bildirimi inceleme bekliyor.`)}
async function load(){const {data,error}=await client.from('content_reports').select('id,target_type,target_id,reason,details,status,created_at').order('created_at',{ascending:false}).limit(200);if(error)throw error;reports=data;parents=new Map();const commentIds=data.filter(x=>x.target_type==='comment').map(x=>x.target_id),answerIds=data.filter(x=>x.target_type==='answer').map(x=>x.target_id);const [comments,answers]=await Promise.all([commentIds.length?client.from('community_comments').select('id,post_id').in('id',commentIds):Promise.resolve({data:[]}),answerIds.length?client.from('colleague_answers').select('id,question_id').in('id',answerIds):Promise.resolve({data:[]})]);for(const x of comments.data||[])parents.set(x.id,x.post_id);for(const x of answers.data||[])parents.set(x.id,x.question_id);render()}
async function init(){if(!client)return;const {data:{session}}=await client.auth.getSession();user=session?.user;if(!user)return;const {data,error}=await client.rpc('is_community_moderator');if(error||!data)return;$('#reportAdminArea').hidden=false;try{await load()}catch(e){status('Bildirimler yüklenemedi. 017 SQL dosyasını kontrol et: '+e.message)}}
$('#reportFilter').addEventListener('change',render);
$('#reportAdminList').addEventListener('click',async e=>{const b=e.target.closest('[data-report-decision]');if(!b)return;b.disabled=true;try{const {data:{user:verified},error:authError}=await client.auth.getUser();if(authError||verified?.id!==user.id)throw Error('Yeniden giriş yap.');const payload=b.dataset.reportDecision==='open'?{status:'open',reviewer_id:null,reviewed_at:null}:{status:b.dataset.reportDecision,reviewer_id:user.id,reviewed_at:new Date().toISOString()};const {data,error}=await client.from('content_reports').update(payload).eq('id',b.dataset.reportId).select('id');if(error)throw error;if(!data.length)throw Error('Güncellenemedi.');await load()}catch(error){status(error.message);b.disabled=false}});
await init();
