import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,authConfigured} from './auth-config.js?v=20260925-2';
if(authConfigured&&window.supabase){
 const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
 const dialog=document.createElement('dialog');dialog.className='report-dialog';dialog.innerHTML='<form id="reportForm"><div class="report-head"><h2>İçerik bildir</h2><button type="button" id="reportClose" aria-label="Kapat">×</button></div><p>Bu bildirim yalnızca yöneticiye görünür. Öğrenci adı veya tanınabilir bilgi ekleme.</p><label>Gerekçe<select name="reason"><option>Kişisel veri</option><option>Spam</option><option>Uygunsuz içerik</option><option>Telif hakkı</option><option>Diğer</option></select></label><label>Ek açıklama (isteğe bağlı)<textarea name="details" maxlength="500" rows="3"></textarea></label><button type="submit">Yöneticiye gönder</button><p id="reportStatus" role="status"></p></form>';
 document.body.append(dialog);let target=null;
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-report-type]');if(!b)return;e.preventDefault();e.stopPropagation();const {data:{session}}=await client.auth.getSession();if(!session?.user){location.href='hesap.html';return}target={type:b.dataset.reportType,id:b.dataset.reportId};dialog.querySelector('form').reset();dialog.querySelector('#reportStatus').textContent='';dialog.showModal()});
 dialog.querySelector('#reportClose').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
 dialog.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();if(!target)return;const f=e.currentTarget,b=f.querySelector('[type="submit"]');b.disabled=true;try{const {data:{user},error:authError}=await client.auth.getUser();if(authError||!user)throw Error('Yeniden giriş yap.');const {error}=await client.from('content_reports').insert({reporter_id:user.id,target_type:target.type,target_id:target.id,reason:f.elements.reason.value,details:f.elements.details.value.trim()});if(error)throw error;dialog.close();const notice=document.createElement('p');notice.className='report-toast';notice.textContent='Bildirim yöneticiye iletildi.';document.body.append(notice);setTimeout(()=>notice.remove(),4000)}catch(error){dialog.querySelector('#reportStatus').textContent=error.code==='23505'?'Bu içeriği zaten bildirdin.':error.message}finally{b.disabled=false}});
}
