import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,authConfigured} from './auth-config.js?v=20260925-2';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&quot;',"'":'&#39;'}[c]));
const client=authConfigured&&window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY),form=$('#resourceForm');
let user=null,items=[];
const status=s=>{$('#resourceAdminStatus').textContent=s};
const statusName={draft:'Taslak',published:'Yayında',archived:'Kaldırıldı'};
function validMebUrl(value){try{const u=new URL(value);return u.protocol==='https:'&&/(^|\.)meb\.gov\.tr$/i.test(u.hostname)}catch{return false}}
function toggleKind(){const tool=form.elements.kind.value==='tool';$('.resource-fields-tool').hidden=!tool;$('.resource-fields-library').hidden=tool;form.elements.category.required=tool;form.elements.area.required=!tool;form.elements.topic.required=!tool}
function reset(){form.reset();form.elements.id.value='';$('#resourceFormHeading').textContent='Yeni kaynak';toggleKind()}
function showList(){const kind=$('#resourceKindFilter').value,filter=$('#resourceStatusFilter').value;const list=items.filter(x=>(!kind||x.kind===kind)&&(!filter||x.status===filter));$('#resourceList').innerHTML=list.length?list.map(x=>`<article class="resource-row"><div><small>${x.kind==='tool'?'Araç Kutusu · '+esc(x.group_name)+' / '+esc(x.category):'Kütüphane · '+esc(x.area)+' / '+esc(x.topic)} · ${esc(x.level)}</small><strong>${esc(x.title)}</strong><span class="resource-status ${esc(x.status)}">${statusName[x.status]}</span></div><div class="resource-row-actions"><a href="${esc(x.file_url)}" target="_blank" rel="noopener noreferrer">Dosyayı kontrol et ↗</a><button data-edit="${esc(x.id)}">Düzenle</button></div></article>`).join(''):'<p class="workspace-empty">Bu filtrede kayıt yok.</p>'}
async function load(){const {data,error}=await client.from('curated_resources').select('*').order('created_at',{ascending:false}).limit(500);if(error)throw error;items=data;showList();status(`${items.length} ek kaynak listelendi.`)}
async function init(){if(!client){status('Bağlantı kurulmadı.');return}const {data:{session}}=await client.auth.getSession();user=session?.user;if(!user){status('Bu alan için giriş yap.');return}const {data,error}=await client.rpc('is_community_moderator');if(error||!data){status('Bu alan yalnızca yöneticiye açık.');return}$('#resourceAdminArea').hidden=false;toggleKind();try{await load()}catch(e){status('Kayıtlar yüklenemedi. 015 SQL dosyasını kontrol et: '+e.message)}}
form.elements.kind.addEventListener('change',toggleKind);$('#resourceReset').addEventListener('click',reset);$('#resourceKindFilter').addEventListener('change',showList);$('#resourceStatusFilter').addEventListener('change',showList);
$('#resourceList').addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(!b)return;const x=items.find(r=>r.id===b.dataset.edit);if(!x)return;reset();for(const name of ['id','kind','title','code','group_name','category','location','area','topic','level','resource_type','file_type','file_url','source_page_url','status'])if(form.elements[name])form.elements[name].value=x[name]??'';toggleKind();$('#resourceFormHeading').textContent='Kaynağı düzenle';form.scrollIntoView({behavior:'smooth',block:'start'})});
form.addEventListener('submit',async e=>{e.preventDefault();if(!user)return;const f=form.elements,file=f.file_url.value.trim(),source=f.source_page_url.value.trim();if(!validMebUrl(file)||source&&!validMebUrl(source)){status('Dosya ve kaynak adresleri HTTPS ile açılan meb.gov.tr alan adında olmalı.');return}const tool=f.kind.value==='tool',payload={kind:f.kind.value,title:f.title.value.trim(),code:tool?f.code.value.trim():'',group_name:tool?f.group_name.value:null,category:tool?f.category.value.trim():null,location:tool?f.location.value:null,area:tool?null:f.area.value.trim(),topic:tool?null:f.topic.value.trim(),level:f.level.value,resource_type:tool?'Form':f.resource_type.value,file_type:f.file_type.value,file_url:file,source_page_url:source||null,status:f.status.value,updated_at:new Date().toISOString()};const button=form.querySelector('[type="submit"]');button.disabled=true;status('Kaydediliyor…');try{const {data:{user:verified},error:authError}=await client.auth.getUser();if(authError||verified?.id!==user.id)throw Error('Yeniden giriş yap.');const request=f.id.value?client.from('curated_resources').update(payload).eq('id',f.id.value):client.from('curated_resources').insert(payload);const {data,error}=await request.select('id');if(error)throw error;if(!data?.length)throw Error('Kaynak kaydedilemedi.');reset();await load();status('Kaynak kaydedildi.'+(payload.status==='published'?' Kataloglarda görünecek.':''))}catch(error){status(error.message)}finally{button.disabled=false}});
await init();
