// Transparent catalogue matching. This module never infers a student's condition.
export const normalize=text=>String(text??'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i');
const stop=new Set(['sinif','sinifta','sinifi','icin','ile','bir','ve','ne','yapmaliyim','suphesi','suphe','ogrenci','ogrencide','hakkinda','ortaokul','ilkokul','lise','okul','oncesi']);
const topics=[
 {name:'Akran zorbalığı',terms:['akran zorbaligi','zorbalik'],related:['sosyometri','ogrenci gozlem kaydi','siddet sikligi anketi','siddet algisi anketi'],explanation:'Konuya yakın araç; kullanım koşullarını belge üzerinden değerlendirin.'},
 {name:'Devamsızlık',terms:['devamsizlik','okula devam'],related:['okul risk'],explanation:'Devamsızlıkla ilişkili kayıt veya izleme aracı.'},
 {name:'Sınav kaygısı',terms:['sinav kaygisi'],related:[],explanation:''},
 {name:'RİBA',terms:['riba','rehberlik ihtiyaci'],related:[],explanation:''},
 {name:'Sosyometri',terms:['sosyometri'],related:[],explanation:''},
 {name:'Özel eğitim',terms:['ozel egitim'],related:[],explanation:''}
];
export function parseQuery(query){const q=normalize(query);const grade=Number(q.match(/\b(1[0-2]|[1-9])\.?\s*sinif(?:ta|i|in)?\b/)?.[1]||0);let level=grade?(grade<=4?'İlkokul':grade<=8?'Ortaokul':'Lise'):null;if(!level){if(q.includes('okul oncesi'))level='Okul öncesi';else if(q.includes('ortaokul'))level='Ortaokul';else if(q.includes('ilkokul'))level='İlkokul';else if(q.includes('lise'))level='Lise'}const topic=topics.find(x=>x.terms.some(t=>q.includes(t)))||null;const words=q.replace(/\b(?:1[0-2]|[1-9])\.?\s*sinif(?:ta|i|in)?\b/g,' ').split(/[^a-z0-9]+/).filter(w=>w.length>2&&!stop.has(w));return {grade,level,topic,words}}
export function searchCatalogs(query,forms,resources){const parsed=parseQuery(query);const results=[];for(const [kind,items] of [['form',forms],['resource',resources]])for(const item of items){const title=normalize(item.title),topic=normalize(item.topic),hay=normalize([item.title,item.code,item.category,item.group,item.area,item.topic,item.type].filter(Boolean).join(' '));if(parsed.level&&item.level&&item.level!=='Belirtilmiyor'&&item.level!=='Tüm kademeler'&&item.level!==parsed.level)continue;const range=title.match(/\b([1-9]|1[0-2])\s*[-–]\s*([1-9]|1[0-2])\.?\s*sinif\b/);if(parsed.grade&&range&&(parsed.grade<Number(range[1])||parsed.grade>Number(range[2])))continue;const exactTopic=parsed.topic&&parsed.topic.terms.some(t=>title.includes(t)||topic.includes(t));const related=parsed.topic&&parsed.topic.related.some(t=>title.includes(t));const hits=parsed.words.filter(w=>hay.includes(w)).length;let relation=null,reason='',score=0;if(exactTopic){relation='direct';score=30;reason=parsed.topic.name+' konusunda kaynak'}else if(related){relation='related';score=12;reason=parsed.topic.explanation}else if(hits>0){relation='direct';score=hits*5;reason='Aradığınız terim belge adında veya başlığında geçiyor'}else if(parsed.level&&kind==='resource'&&item.type==='Etkinlik kitabı'&&parsed.topic?.name==='Akran zorbalığı'){relation='general';score=2;reason=parsed.level+' için genel sınıf rehberliği kaynağı'}else if(parsed.level&&!parsed.topic&&parsed.words.length===0&&item.level===parsed.level){relation='direct';score=4;reason=parsed.level+' kademesi'}if(!relation)continue;if(parsed.level&&item.level===parsed.level){score+=7;reason+=' · '+parsed.level}if(parsed.level&&item.level==='Belirtilmiyor')reason+=' · kademe kaynakta belirtilmiyor';results.push({item,kind,relation,reason,score})}results.sort((a,b)=>b.score-a.score||a.item.title.localeCompare(b.item.title,'tr'));return {parsed,results}}
