import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,authConfigured} from './auth-config.js?v=20260925-2';
const $=selector=>document.querySelector(selector);
const client=authConfigured&&window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const allowed=new Map([['pdf','application/pdf'],['docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document'],['pptx','application/vnd.openxmlformats-officedocument.presentationml.presentation']]);
const bucket='community-documents';
let ready=false,currentUser=null;
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderItem(item,own=false){return `<article class="document-card"><div class="document-card-meta"><span>Meslektaş paylaşımı</span><span>${escapeHTML(item.document_type)}</span></div><h3>${escapeHTML(item.title)}</h3><p>${escapeHTML(item.topic)} · ${escapeHTML(item.level)}</p><div><small>${own?item.review_status==='pending'?'İncelemede':item.review_status==='approved'?'Yayında':'Yayımlanmadı':'İncelenmiş paylaşım'}</small>${item.review_status==='approved'?`<button data-community-file="${escapeHTML(item.file_storage_key)}">Dosyayı aç ↗</button>`:''}</div></article>`}
async function refreshList(){const {data,error}=await client.from('community_documents').select('title,document_type,level,topic,file_storage_key,review_status,created_at').eq('review_status','approved').order('created_at',{ascending:false}).limit(30);if(error)throw error;$('#communityList').innerHTML=data.length?data.map(x=>renderItem(x)).join(''):'<p class="empty">Henüz incelenip yayımlanmış meslektaş belgesi yok.</p>';$('#communityListStatus').textContent=data.length===30?'Son 30 belge gösteriliyor.':''}
async function refreshOwn(){if(!currentUser){$('#myDocuments').hidden=true;return}const {data,error}=await client.from('community_documents').select('title,document_type,level,topic,file_storage_key,review_status,created_at').eq('uploader_id',currentUser.id).order('created_at',{ascending:false}).limit(20);if(error)throw error;$('#myDocuments').hidden=false;$('#myDocumentsList').innerHTML=data.length?data.map(x=>renderItem(x,true)).join(''):'<p>Henüz belge göndermedin.</p>'}
async function refreshSession(){if(!ready)return;const {data:{session}}=await client.auth.getSession();currentUser=session?.user||null;$('#uploadForm').hidden=!currentUser;$('#uploadLogin').hidden=!!currentUser;await refreshOwn()}
if(!client){$('#uploadSetup').hidden=false;$('#uploadSetup').textContent='Belge paylaşımı için hesap bağlantısı kurulmalı.'}
else {
  const {error}=await client.from('community_documents').select('id').limit(1);
  if(error){$('#uploadSetup').hidden=false;$('#uploadSetup').textContent='Belge paylaşımı henüz kurulmadı. İnceleme ve depolama tabloları hazırlandığında açılacak.'}
  else {ready=true;$('#communityLayout').hidden=false;await Promise.all([refreshList(),refreshSession()]);client.auth.onAuthStateChange(()=>setTimeout(()=>refreshSession().catch(()=>{}),0));}
}
$('#uploadForm').addEventListener('submit',async e=>{e.preventDefault();if(!ready||!currentUser)return;const form=e.currentTarget,fields=new FormData(form),file=fields.get('file'),extension=String(file?.name||'').split('.').pop().toLowerCase();const mime=allowed.get(extension);if(!mime||file.type!==mime||file.size<1||file.size>20971520){$('#uploadStatus').textContent='PDF, DOCX veya PPTX biçiminde en çok 20 MB dosya seç.';return}const button=form.querySelector('button[type="submit"]');button.disabled=true;$('#uploadStatus').textContent='Dosya güvenli alana yükleniyor…';const path=`${currentUser.id}/${crypto.randomUUID()}.${extension}`;try{const {data:{user},error:authError}=await client.auth.getUser();if(authError||user?.id!==currentUser.id)throw Error('Oturumun süresi dolmuş. Yeniden giriş yap.');const {error:uploadError}=await client.storage.from(bucket).upload(path,file,{contentType:mime,upsert:false});if(uploadError)throw uploadError;const record={uploader_id:user.id,title:String(fields.get('title')).trim(),document_type:String(fields.get('document_type')),level:String(fields.get('level')),topic:String(fields.get('topic')).trim(),file_storage_key:path,original_filename:file.name,mime_type:mime,size_bytes:file.size,rights_confirmed:fields.get('rights')==='on'};const {error:insertError}=await client.from('community_documents').insert(record);if(insertError){await client.storage.from(bucket).remove([path]);throw insertError}form.reset();$('#uploadStatus').textContent='Belge inceleme kuyruğuna alındı. Onaylanmadan yayımlanmaz.';await refreshOwn()}catch(error){$('#uploadStatus').textContent=error.message||'Yükleme tamamlanamadı.'}finally{button.disabled=false}});
document.addEventListener('click',async e=>{const button=e.target.closest('[data-community-file]');if(!button||!ready)return;button.disabled=true;const previous=button.textContent;button.textContent='Bağlantı hazırlanıyor…';try{const {data,error}=await client.storage.from(bucket).createSignedUrl(button.dataset.communityFile,60);if(error)throw error;window.location.assign(data.signedUrl)}catch(error){$('#communityListStatus').textContent='Dosya açılamadı: '+error.message;button.disabled=false;button.textContent=previous}});
