import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,authConfigured} from './auth-config.js?v=20260925-2';
const $=s=>document.querySelector(s),client=authConfigured&&window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY),bucket='community-documents';
const allowed=new Map([['pdf','application/pdf'],['docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document'],['pptx','application/vnd.openxmlformats-officedocument.presentationml.presentation']]);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let ready=false,user=null;
async function renderList(){const {data,error}=await client.from('community_documents').select('title,document_type,level,topic,file_storage_key,uploader_id').eq('review_status','approved').order('created_at',{ascending:false}).limit(30);if(error)throw error;let names=new Map();if(data.length){const {data:members}=await client.rpc('get_member_profiles',{member_ids:[...new Set(data.map(x=>x.uploader_id))]});names=new Map((members||[]).map(x=>[x.id,x.display_name]))}$('#communityList').innerHTML=data.length?data.map(x=>`<article class="document-card"><div class="document-card-meta"><span>Meslektaş paylaşımı</span><span>${esc(x.document_type)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.topic)} · ${esc(x.level)}</p><div><a href="profil.html?id=${encodeURIComponent(x.uploader_id)}">${esc(names.get(x.uploader_id)||'Üye profili')}</a><button data-community-file="${esc(x.file_storage_key)}">Dosyayı aç ↗</button></div></article>`).join(''):'<p class="empty">Henüz yayımlanmış meslektaş belgesi yok.</p>'}
async function refreshSession(){const {data:{session}}=await client.auth.getSession();user=session?.user||null;$('#uploadForm').hidden=!user;$('#uploadLogin').hidden=!!user;$('#profileShortcut').hidden=!user}
if(!client){$('#uploadSetup').hidden=false;$('#uploadSetup').textContent='Belge paylaşımı için hesap bağlantısı kurulmalı.'}
else {const {error}=await client.from('community_documents').select('id').limit(1);if(error){$('#uploadSetup').hidden=false;$('#uploadSetup').textContent='Belge paylaşımı henüz kurulmadı.'}else{ready=true;$('#communityLayout').hidden=false;await Promise.all([renderList(),refreshSession()]);client.auth.onAuthStateChange(()=>setTimeout(()=>refreshSession().catch(()=>{}),0))}}
$('#uploadForm').addEventListener('submit',async e=>{e.preventDefault();if(!ready||!user)return;const form=e.currentTarget,fields=new FormData(form),file=fields.get('file'),extension=String(file?.name||'').split('.').pop().toLowerCase(),mime=allowed.get(extension);if(!mime||file.type!==mime||file.size<1||file.size>20971520){$('#uploadStatus').textContent='PDF, DOCX veya PPTX biçiminde en çok 20 MB dosya seç.';return}const button=form.querySelector('button[type="submit"]');button.disabled=true;$('#uploadStatus').textContent='Yükleniyor…';const path=`${user.id}/${crypto.randomUUID()}.${extension}`;try{const {data:{user:verified},error:authError}=await client.auth.getUser();if(authError||verified?.id!==user.id)throw Error('Yeniden giriş yap.');const {error:uploadError}=await client.storage.from(bucket).upload(path,file,{contentType:mime,upsert:false});if(uploadError)throw uploadError;const {error:insertError}=await client.from('community_documents').insert({uploader_id:user.id,title:String(fields.get('title')).trim(),document_type:String(fields.get('document_type')),level:String(fields.get('level')),topic:String(fields.get('topic')).trim(),file_storage_key:path,original_filename:file.name,mime_type:mime,size_bytes:file.size,rights_confirmed:fields.get('rights')==='on'});if(insertError){await client.storage.from(bucket).remove([path]);throw insertError}form.reset();$('#uploadStatus').innerHTML='Belge incelemeye alındı. Durumunu <a href="profil.html">profilinde gör ↗</a>'}catch(error){$('#uploadStatus').textContent=error.message||'Yükleme tamamlanamadı.'}finally{button.disabled=false}});
document.addEventListener('click',async e=>{const button=e.target.closest('[data-community-file]');if(!button||!ready)return;button.disabled=true;const previous=button.textContent;button.textContent='Açılıyor…';try{const {data,error}=await client.storage.from(bucket).createSignedUrl(button.dataset.communityFile,300);if(error)throw error;const file=button.dataset.communityFile,title=button.closest('.document-card')?.querySelector('h3')?.textContent||'Meslektaş belgesi';$('#viewerCode').textContent='MESLEKTAŞ PAYLAŞIMI · '+(file.endsWith('.pdf')?'PDF':'DOSYA');$('#viewerTitle').textContent=title;$('#viewerOpen').href=data.signedUrl;$('#viewerBody').innerHTML=file.endsWith('.pdf')?`<iframe title="${esc(title)}" src="${esc(data.signedUrl)}#toolbar=1" loading="lazy"></iframe>`:'<div class="file-message"><strong>Önizleme yok</strong><p>Dosyayı alt bağlantıdan aç veya indir.</p></div>';$('#viewerDialog').showModal()}catch(error){$('#communityListStatus').textContent='Dosya açılamadı: '+error.message}finally{button.disabled=false;button.textContent=previous}});
