import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,authConfigured} from './auth-config.js?v=20260925-2';
const $=selector=>document.querySelector(selector);
const client=authConfigured&&window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const allowed=new Map([['pdf','application/pdf'],['docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document'],['pptx','application/vnd.openxmlformats-officedocument.presentationml.presentation']]);
const bucket='community-documents';
let ready=false,currentUser=null,isModerator=false;
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderItem(item,own=false){return `<article class="document-card"><div class="document-card-meta"><span>Meslektaş paylaşımı</span><span>${escapeHTML(item.document_type)}</span></div><h3>${escapeHTML(item.title)}</h3><p>${escapeHTML(item.topic)} · ${escapeHTML(item.level)}</p><div><small>${own?item.review_status==='pending'?'İncelemede':item.review_status==='approved'?'Yayında':'Yayımlanmadı':'İncelenmiş paylaşım'}</small>${own&&item.review_status==='rejected'&&item.review_note?`<span class="review-reason">Gerekçe: ${escapeHTML(item.review_note)}</span>`:''}${item.review_status==='approved'?`<button data-community-file="${escapeHTML(item.file_storage_key)}">Dosyayı aç ↗</button>`:''}</div></article>`}
async function refreshList(){const {data,error}=await client.from('community_documents').select('title,document_type,level,topic,file_storage_key,review_status,created_at').eq('review_status','approved').order('created_at',{ascending:false}).limit(30);if(error)throw error;$('#communityList').innerHTML=data.length?data.map(x=>renderItem(x)).join(''):'<p class="empty">Henüz incelenip yayımlanmış meslektaş belgesi yok.</p>';$('#communityListStatus').textContent=data.length===30?'Son 30 belge gösteriliyor.':''}
async function refreshOwn(){if(!currentUser){$('#myDocuments').hidden=true;return}const {data,error}=await client.from('community_documents').select('title,document_type,level,topic,file_storage_key,review_status,review_note,created_at').eq('uploader_id',currentUser.id).order('created_at',{ascending:false}).limit(20);if(error)throw error;$('#myDocuments').hidden=false;$('#myDocumentsList').innerHTML=data.length?data.map(x=>renderItem(x,true)).join(''):'<p>Henüz belge göndermedin.</p>'}
async function refreshReviews(){if(!isModerator)return;const {data,error}=await client.from('community_documents').select('id,title,document_type,level,topic,original_filename,file_storage_key,created_at').eq('review_status','pending').order('created_at',{ascending:true}).limit(30);if(error)throw error;$('#reviewStatus').textContent=data.length?`${data.length} belge inceleme bekliyor.`:'Bekleyen belge yok.';$('#reviewList').innerHTML=data.map(item=>`<article class="review-card" data-review-id="${escapeHTML(item.id)}"><div><strong>${escapeHTML(item.title)}</strong><p>${escapeHTML(item.document_type)} · ${escapeHTML(item.level)} · ${escapeHTML(item.topic)}</p><small>${escapeHTML(item.original_filename)}</small></div><button type="button" data-community-file="${escapeHTML(item.file_storage_key)}">Dosyayı aç ↗</button><label>İnceleme notu<textarea rows="2" maxlength="500" placeholder="Ret için gerekçe yaz"></textarea></label><div class="review-actions"><button type="button" data-decision="approved">Onayla</button><button type="button" data-decision="rejected">Reddet</button></div></article>`).join('')}
async function refreshSession(){if(!ready)return;const {data:{session}}=await client.auth.getSession();currentUser=session?.user||null;$('#uploadForm').hidden=!currentUser;$('#uploadLogin').hidden=!!currentUser;isModerator=false;$('#reviewPanel').hidden=true;await refreshOwn();if(currentUser){const {data,error}=await client.rpc('is_community_moderator');if(!error&&data){isModerator=true;$('#reviewPanel').hidden=false;await refreshReviews()}}}
if(!client){$('#uploadSetup').hidden=false;$('#uploadSetup').textContent='Belge paylaşımı için hesap bağlantısı kurulmalı.'}
else {
  const {error}=await client.from('community_documents').select('id').limit(1);
  if(error){$('#uploadSetup').hidden=false;$('#uploadSetup').textContent='Belge paylaşımı henüz kurulmadı. İnceleme ve depolama tabloları hazırlandığında açılacak.'}
  else {ready=true;$('#communityLayout').hidden=false;await Promise.all([refreshList(),refreshSession()]);client.auth.onAuthStateChange(()=>setTimeout(()=>refreshSession().catch(()=>{}),0));}
}
$('#uploadForm').addEventListener('submit',async e=>{e.preventDefault();if(!ready||!currentUser)return;const form=e.currentTarget,fields=new FormData(form),file=fields.get('file'),extension=String(file?.name||'').split('.').pop().toLowerCase();const mime=allowed.get(extension);if(!mime||file.type!==mime||file.size<1||file.size>20971520){$('#uploadStatus').textContent='PDF, DOCX veya PPTX biçiminde en çok 20 MB dosya seç.';return}const button=form.querySelector('button[type="submit"]');button.disabled=true;$('#uploadStatus').textContent='Dosya güvenli alana yükleniyor…';const path=`${currentUser.id}/${crypto.randomUUID()}.${extension}`;try{const {data:{user},error:authError}=await client.auth.getUser();if(authError||user?.id!==currentUser.id)throw Error('Oturumun süresi dolmuş. Yeniden giriş yap.');const {error:uploadError}=await client.storage.from(bucket).upload(path,file,{contentType:mime,upsert:false});if(uploadError)throw uploadError;const record={uploader_id:user.id,title:String(fields.get('title')).trim(),document_type:String(fields.get('document_type')),level:String(fields.get('level')),topic:String(fields.get('topic')).trim(),file_storage_key:path,original_filename:file.name,mime_type:mime,size_bytes:file.size,rights_confirmed:fields.get('rights')==='on'};const {error:insertError}=await client.from('community_documents').insert(record);if(insertError){await client.storage.from(bucket).remove([path]);throw insertError}form.reset();$('#uploadStatus').textContent='Belge inceleme kuyruğuna alındı. Onaylanmadan yayımlanmaz.';await refreshOwn()}catch(error){$('#uploadStatus').textContent=error.message||'Yükleme tamamlanamadı.'}finally{button.disabled=false}});
document.addEventListener('click',async e=>{const button=e.target.closest('[data-community-file]');if(!button||!ready)return;button.disabled=true;const previous=button.textContent;button.textContent='Bağlantı hazırlanıyor…';try{const {data,error}=await client.storage.from(bucket).createSignedUrl(button.dataset.communityFile,300);if(error)throw error;const file=button.dataset.communityFile;const title=button.closest('.document-card,.review-card')?.querySelector('h3,strong')?.textContent||'Meslektaş belgesi';$('#viewerCode').textContent='MESLEKTAŞ PAYLAŞIMI · '+(file.endsWith('.pdf')?'PDF':'DOSYA');$('#viewerTitle').textContent=title;$('#viewerOpen').href=data.signedUrl;$('#viewerBody').innerHTML=file.endsWith('.pdf')?`<iframe title="${escapeHTML(title)}" src="${escapeHTML(data.signedUrl)}#toolbar=1" loading="lazy"></iframe>`:'<div class="file-message"><strong>Önizleme yok</strong><p>Bu dosya türü tarayıcıda görüntülenemiyor. Aşağıdaki “Dosyayı aç / indir” bağlantısını kullan.</p></div>';$('#viewerDialog').showModal();button.disabled=false;button.textContent=previous}catch(error){$('#communityListStatus').textContent='Dosya açılamadı: '+error.message;button.disabled=false;button.textContent=previous}});


document.addEventListener('click',async e=>{const button=e.target.closest('[data-decision]');if(!button||!ready||!isModerator||!currentUser)return;const card=button.closest('[data-review-id]'),decision=button.dataset.decision,note=card.querySelector('textarea').value.trim();if(decision==='rejected'&&!note){$('#reviewStatus').textContent='Reddetmek için gerekçe yaz.';card.querySelector('textarea').focus();return}button.disabled=true;$('#reviewStatus').textContent='Karar kaydediliyor…';try{const {data:{user},error:authError}=await client.auth.getUser();if(authError||user?.id!==currentUser.id)throw Error('Oturumunu yenile.');const {data,error}=await client.from('community_documents').update({review_status:decision,reviewer_id:user.id,reviewed_at:new Date().toISOString(),review_note:note||'İçerik incelendi'}).eq('id',card.dataset.reviewId).eq('review_status','pending').select('id');if(error)throw error;if(!data.length)throw Error('Bu belge başka bir işlemle güncellenmiş.');await Promise.all([refreshReviews(),refreshList(),refreshOwn()]);$('#reviewStatus').textContent=decision==='approved'?'Belge yayımlandı.':'Belge reddedildi.'}catch(error){$('#reviewStatus').textContent=error.message||'Karar kaydedilemedi.';button.disabled=false}});
