import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,authConfigured} from './auth-config.js?v=20260925-2';
import {getCuratedResources} from './curated.js?v=20260926-1';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&quot;',"'":'&#39;'}[c]));
const client=authConfigured&&window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let user=null,notes=[],tasks=[],saved=[];
const status=s=>{$('#workspaceStatus').textContent=s};
async function readCatalog(path){try{const r=await fetch(path);return r.ok?await r.json():[]}catch{return []}}
async function load(){const [n,t,s,own,reactions,forms,library,curated]=await Promise.all([
 client.from('workspace_notes').select('id,title,body,updated_at').eq('owner_id',user.id).order('updated_at',{ascending:false}).limit(100),
 client.from('workspace_tasks').select('id,title,due_date,completed').eq('owner_id',user.id).order('completed',{ascending:true}).order('due_date',{ascending:true,nullsFirst:false}).limit(100),
 client.from('workspace_saved_items').select('kind,ref_id').eq('owner_id',user.id).order('created_at',{ascending:false}).limit(200),
 client.from('community_documents').select('title,review_status,created_at').eq('uploader_id',user.id).order('created_at',{ascending:false}).limit(10),
 client.from('community_reactions').select('post_id').eq('user_id',user.id).eq('kind','save').limit(100),
 readCatalog('data/forms.json'),readCatalog('data/library.json'),getCuratedResources()]);
 const failure=[n,t,s,own,reactions].find(x=>x.error);if(failure)throw failure.error;notes=n.data;tasks=t.data;saved=s.data;
 $('#taskCount').textContent=tasks.filter(x=>!x.completed).length;$('#noteCount').textContent=notes.length;$('#savedCount').textContent=saved.length;
 $('#taskList').innerHTML=tasks.length?tasks.map(x=>`<div class="workspace-row ${x.completed?'is-done':''}"><label><input type="checkbox" data-task-toggle="${esc(x.id)}" ${x.completed?'checked':''}><span>${esc(x.title)}</span></label><small>${x.due_date?new Date(x.due_date+'T12:00:00').toLocaleDateString('tr-TR'):'Tarih yok'}</small><button type="button" data-task-delete="${esc(x.id)}" aria-label="İşi sil">×</button></div>`).join(''):'<p class="workspace-empty">Henüz planlanmış iş yok.</p>';
 $('#noteList').innerHTML=notes.length?notes.map(x=>`<details class="workspace-note" data-note="${esc(x.id)}"><summary><strong>${esc(x.title)}</strong><small>${new Date(x.updated_at).toLocaleDateString('tr-TR')}</small></summary><div class="workspace-note-editor"><label>Başlık<input name="title" maxlength="120" value="${esc(x.title)}"></label><label>Not<textarea name="body" maxlength="3000">${esc(x.body)}</textarea></label><div><button type="button" data-note-save>Kaydet</button><button type="button" data-note-delete>Sil</button></div></div></details>`).join(''):'<p class="workspace-empty">Henüz not eklemedin.</p>';
 const formsById=new Map([...forms,...curated.tools].map(x=>[String(x.id),x])),libraryById=new Map([...library,...curated.library].map(x=>[String(x.id),x]));const keys=saved.filter(x=>x.kind==='community_file').map(x=>x.ref_id);
 const files=keys.length?await client.from('community_documents').select('id,title,file_storage_key').in('file_storage_key',keys).eq('review_status','approved'):{data:[],error:null};if(files.error)throw files.error;const filesByKey=new Map(files.data.map(x=>[x.file_storage_key,x]));
 $('#savedList').innerHTML=saved.length?saved.map(x=>{const item=x.kind==='tool'?formsById.get(x.ref_id):x.kind==='library'?libraryById.get(x.ref_id):filesByKey.get(x.ref_id),href=x.kind==='tool'?`kutuphane.html?tur=Form#${encodeURIComponent(x.ref_id)}`:x.kind==='library'?`kutuphane.html#${encodeURIComponent(x.ref_id)}`:item?.id?`kutuphane.html#belge-${encodeURIComponent(item.id)}`:'kutuphane.html?kaynak=member',label=x.kind==='tool'?'Form':x.kind==='library'?'Kaynak':'Üye belgesi';return `<div class="workspace-saved-row"><div><small>${label}</small><a href="${href}">${esc(item?.title||'Artık erişilemeyen kayıt')} ↗</a></div><button type="button" data-unsave="${esc(x.kind)}" data-ref="${esc(x.ref_id)}" aria-label="Kaydı kaldır">Kaldır</button></div>`}).join(''):'<p class="workspace-empty">Araç veya belge kartındaki Kaydet düğmesinden kaynak ekleyebilirsin.</p>';
 const postIds=reactions.data.map(x=>x.post_id),posts=postIds.length?await client.from('community_posts').select('id,title').in('id',postIds).eq('status','published'):{data:[],error:null};if(posts.error)throw posts.error;$('#savedPosts').innerHTML=posts.data.length?posts.data.map(x=>`<a class="workspace-link" href="topluluk.html#gonderi-${encodeURIComponent(x.id)}">${esc(x.title)} ↗</a>`).join(''):'<p class="workspace-empty">Henüz gönderi kaydetmedin.</p>';
 const labels={pending:'İncelemede',approved:'Yayında',rejected:'Reddedildi',archived:'Yayından kaldırıldı'};$('#myDocuments').innerHTML=own.data.length?own.data.map(x=>`<a class="workspace-link" href="profil.html">${esc(x.title)} <small>${esc(labels[x.review_status])}</small></a>`).join(''):'<p class="workspace-empty">Henüz belge yüklemedin.</p>';
}
async function verify(){const {data:{user:verified},error}=await client.auth.getUser();if(error||verified?.id!==user.id)throw Error('Yeniden giriş yap.')}
async function action(run,button){button.disabled=true;try{await verify();await run();await load();status('Değişiklik kaydedildi.')}catch(e){status(e.message)}finally{button.disabled=false}}
async function init(){if(!client){status('Çalışma alanı bağlantısı kurulmadı.');return}const {data:{session}}=await client.auth.getSession();user=session?.user||null;$('#workspaceLogin').hidden=!!user;$('#workspaceContent').hidden=!user;if(!user)return;try{await load()}catch(e){status('Çalışma alanı yüklenemedi. 013 SQL dosyasını kontrol et: '+e.message)}}
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();if(!user)return;const f=e.currentTarget,b=f.querySelector('button'),title=f.elements.title.value.trim(),due_date=f.elements.due_date.value||null;if(title.length<3)return;action(async()=>{const {error}=await client.from('workspace_tasks').insert({owner_id:user.id,title,due_date});if(error)throw error;f.reset()},b)});
$('#noteForm').addEventListener('submit',e=>{e.preventDefault();if(!user)return;const f=e.currentTarget,b=f.querySelector('button'),title=f.elements.title.value.trim(),body=f.elements.body.value.trim();if(title.length<2||!body)return;action(async()=>{const {error}=await client.from('workspace_notes').insert({owner_id:user.id,title,body});if(error)throw error;f.reset()},b)});
$('#workspaceContent').addEventListener('change',e=>{const box=e.target.closest('[data-task-toggle]');if(!box)return;action(async()=>{const {error}=await client.from('workspace_tasks').update({completed:box.checked}).eq('id',box.dataset.taskToggle).eq('owner_id',user.id);if(error)throw error},box)});
$('#workspaceContent').addEventListener('click',e=>{const b=e.target.closest('[data-task-delete],[data-note-delete],[data-note-save],[data-unsave]');if(!b)return;action(async()=>{let result;if(b.dataset.taskDelete)result=await client.from('workspace_tasks').delete().eq('id',b.dataset.taskDelete).eq('owner_id',user.id);else if(b.hasAttribute('data-note-delete'))result=await client.from('workspace_notes').delete().eq('id',b.closest('[data-note]').dataset.note).eq('owner_id',user.id);else if(b.hasAttribute('data-note-save')){const card=b.closest('[data-note]'),title=card.querySelector('[name="title"]').value.trim(),body=card.querySelector('[name="body"]').value.trim();if(title.length<2||!body)throw Error('Başlık ve not boş olamaz.');result=await client.from('workspace_notes').update({title,body,updated_at:new Date().toISOString()}).eq('id',card.dataset.note).eq('owner_id',user.id)}else result=await client.from('workspace_saved_items').delete().eq('owner_id',user.id).eq('kind',b.dataset.unsave).eq('ref_id',b.dataset.ref);if(result.error)throw result.error},b)});
await init();
